// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redsdn.proto

package redsdn

/*
golang配置
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IP 协议版本枚举
type ProtoEndPointAddress_IPVersion int32

const (
	ProtoEndPointAddress_V4 ProtoEndPointAddress_IPVersion = 0
	ProtoEndPointAddress_V6 ProtoEndPointAddress_IPVersion = 1
)

var ProtoEndPointAddress_IPVersion_name = map[int32]string{
	0: "V4",
	1: "V6",
}
var ProtoEndPointAddress_IPVersion_value = map[string]int32{
	"V4": 0,
	"V6": 1,
}

func (x ProtoEndPointAddress_IPVersion) Enum() *ProtoEndPointAddress_IPVersion {
	p := new(ProtoEndPointAddress_IPVersion)
	*p = x
	return p
}
func (x ProtoEndPointAddress_IPVersion) String() string {
	return proto.EnumName(ProtoEndPointAddress_IPVersion_name, int32(x))
}
func (x *ProtoEndPointAddress_IPVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoEndPointAddress_IPVersion_value, data, "ProtoEndPointAddress_IPVersion")
	if err != nil {
		return err
	}
	*x = ProtoEndPointAddress_IPVersion(value)
	return nil
}
func (ProtoEndPointAddress_IPVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{4, 0}
}

type ProtoMulticastLinkInfo_NodeType int32

const (
	ProtoMulticastLinkInfo_USER  ProtoMulticastLinkInfo_NodeType = 0
	ProtoMulticastLinkInfo_RELAY ProtoMulticastLinkInfo_NodeType = 1
)

var ProtoMulticastLinkInfo_NodeType_name = map[int32]string{
	0: "USER",
	1: "RELAY",
}
var ProtoMulticastLinkInfo_NodeType_value = map[string]int32{
	"USER":  0,
	"RELAY": 1,
}

func (x ProtoMulticastLinkInfo_NodeType) Enum() *ProtoMulticastLinkInfo_NodeType {
	p := new(ProtoMulticastLinkInfo_NodeType)
	*p = x
	return p
}
func (x ProtoMulticastLinkInfo_NodeType) String() string {
	return proto.EnumName(ProtoMulticastLinkInfo_NodeType_name, int32(x))
}
func (x *ProtoMulticastLinkInfo_NodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMulticastLinkInfo_NodeType_value, data, "ProtoMulticastLinkInfo_NodeType")
	if err != nil {
		return err
	}
	*x = ProtoMulticastLinkInfo_NodeType(value)
	return nil
}
func (ProtoMulticastLinkInfo_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{6, 0}
}

type ProtoMulticastInfo_OperationType int32

const (
	ProtoMulticastInfo_ADD    ProtoMulticastInfo_OperationType = 0
	ProtoMulticastInfo_REMOVE ProtoMulticastInfo_OperationType = 1
)

var ProtoMulticastInfo_OperationType_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
}
var ProtoMulticastInfo_OperationType_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
}

func (x ProtoMulticastInfo_OperationType) Enum() *ProtoMulticastInfo_OperationType {
	p := new(ProtoMulticastInfo_OperationType)
	*p = x
	return p
}
func (x ProtoMulticastInfo_OperationType) String() string {
	return proto.EnumName(ProtoMulticastInfo_OperationType_name, int32(x))
}
func (x *ProtoMulticastInfo_OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMulticastInfo_OperationType_value, data, "ProtoMulticastInfo_OperationType")
	if err != nil {
		return err
	}
	*x = ProtoMulticastInfo_OperationType(value)
	return nil
}
func (ProtoMulticastInfo_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{7, 0}
}

type ProtoPhysicalLinkChangeNotify_PhysicalLinkState int32

const (
	ProtoPhysicalLinkChangeNotify_ONLINE    ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 0
	ProtoPhysicalLinkChangeNotify_FLASH_OFF ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 1
	ProtoPhysicalLinkChangeNotify_OFFLINE   ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 2
)

var ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name = map[int32]string{
	0: "ONLINE",
	1: "FLASH_OFF",
	2: "OFFLINE",
}
var ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value = map[string]int32{
	"ONLINE":    0,
	"FLASH_OFF": 1,
	"OFFLINE":   2,
}

func (x ProtoPhysicalLinkChangeNotify_PhysicalLinkState) Enum() *ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	p := new(ProtoPhysicalLinkChangeNotify_PhysicalLinkState)
	*p = x
	return p
}
func (x ProtoPhysicalLinkChangeNotify_PhysicalLinkState) String() string {
	return proto.EnumName(ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name, int32(x))
}
func (x *ProtoPhysicalLinkChangeNotify_PhysicalLinkState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value, data, "ProtoPhysicalLinkChangeNotify_PhysicalLinkState")
	if err != nil {
		return err
	}
	*x = ProtoPhysicalLinkChangeNotify_PhysicalLinkState(value)
	return nil
}
func (ProtoPhysicalLinkChangeNotify_PhysicalLinkState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{10, 0}
}

// 消息类型枚举
type ProtoMonitorMessage_MessageType int32

const (
	ProtoMonitorMessage_USER_INFO               ProtoMonitorMessage_MessageType = 0
	ProtoMonitorMessage_RELAY_INFO              ProtoMonitorMessage_MessageType = 1
	ProtoMonitorMessage_MULTICAST_INFO          ProtoMonitorMessage_MessageType = 2
	ProtoMonitorMessage_MULTICAST_EVENT_INFO    ProtoMonitorMessage_MessageType = 3
	ProtoMonitorMessage_NIC_LIST                ProtoMonitorMessage_MessageType = 4
	ProtoMonitorMessage_PHYSICAL_LINK_EVENT     ProtoMonitorMessage_MessageType = 5
	ProtoMonitorMessage_PHYSICAL_LINK_STAT_DATA ProtoMonitorMessage_MessageType = 6
)

var ProtoMonitorMessage_MessageType_name = map[int32]string{
	0: "USER_INFO",
	1: "RELAY_INFO",
	2: "MULTICAST_INFO",
	3: "MULTICAST_EVENT_INFO",
	4: "NIC_LIST",
	5: "PHYSICAL_LINK_EVENT",
	6: "PHYSICAL_LINK_STAT_DATA",
}
var ProtoMonitorMessage_MessageType_value = map[string]int32{
	"USER_INFO":               0,
	"RELAY_INFO":              1,
	"MULTICAST_INFO":          2,
	"MULTICAST_EVENT_INFO":    3,
	"NIC_LIST":                4,
	"PHYSICAL_LINK_EVENT":     5,
	"PHYSICAL_LINK_STAT_DATA": 6,
}

func (x ProtoMonitorMessage_MessageType) Enum() *ProtoMonitorMessage_MessageType {
	p := new(ProtoMonitorMessage_MessageType)
	*p = x
	return p
}
func (x ProtoMonitorMessage_MessageType) String() string {
	return proto.EnumName(ProtoMonitorMessage_MessageType_name, int32(x))
}
func (x *ProtoMonitorMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMonitorMessage_MessageType_value, data, "ProtoMonitorMessage_MessageType")
	if err != nil {
		return err
	}
	*x = ProtoMonitorMessage_MessageType(value)
	return nil
}
func (ProtoMonitorMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{15, 0}
}

// =============================================================================================================================
// 物理链路基础信息
// @since 1.0
type ProtoPhysicalLinkInfo struct {
	PhysicalLinkId       *string  `protobuf:"bytes,1,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	Direction            *uint32  `protobuf:"varint,2,req,name=direction" json:"direction,omitempty"`
	LocalNetType         *uint32  `protobuf:"varint,3,req,name=local_net_type" json:"local_net_type,omitempty"`
	LocalAddr            *string  `protobuf:"bytes,4,req,name=local_addr" json:"local_addr,omitempty"`
	DestNetType          *uint32  `protobuf:"varint,5,req,name=dest_net_type" json:"dest_net_type,omitempty"`
	DestAddr             *string  `protobuf:"bytes,6,req,name=dest_addr" json:"dest_addr,omitempty"`
	RoleType             *uint32  `protobuf:"varint,7,req,name=role_type" json:"role_type,omitempty"`
	TickTime             *uint64  `protobuf:"varint,8,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime              *uint64  `protobuf:"varint,9,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoPhysicalLinkInfo) Reset()         { *m = ProtoPhysicalLinkInfo{} }
func (m *ProtoPhysicalLinkInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkInfo) ProtoMessage()    {}
func (*ProtoPhysicalLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{0}
}
func (m *ProtoPhysicalLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkInfo.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkInfo.Merge(dst, src)
}
func (m *ProtoPhysicalLinkInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkInfo.Size(m)
}
func (m *ProtoPhysicalLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkInfo proto.InternalMessageInfo

func (m *ProtoPhysicalLinkInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetLocalNetType() uint32 {
	if m != nil && m.LocalNetType != nil {
		return *m.LocalNetType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetLocalAddr() string {
	if m != nil && m.LocalAddr != nil {
		return *m.LocalAddr
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetDestNetType() uint32 {
	if m != nil && m.DestNetType != nil {
		return *m.DestNetType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetDestAddr() string {
	if m != nil && m.DestAddr != nil {
		return *m.DestAddr
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// 物理链路质量
// @since 1.0
type ProtoPhysicalLinkQuality struct {
	PhysicalLinkId              *string  `protobuf:"bytes,1,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	Idx                         *uint32  `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	Rtt                         *uint32  `protobuf:"varint,3,req,name=rtt" json:"rtt,omitempty"`
	LossRate                    *uint32  `protobuf:"varint,4,req,name=loss_rate" json:"loss_rate,omitempty"`
	Jitter                      *uint32  `protobuf:"varint,5,req,name=jitter" json:"jitter,omitempty"`
	Direction                   *uint32  `protobuf:"varint,6,req,name=direction" json:"direction,omitempty"`
	BandWidth                   *uint32  `protobuf:"varint,7,req,name=band_width" json:"band_width,omitempty"`
	AllocBandWidth              *uint32  `protobuf:"varint,8,req,name=alloc_band_width" json:"alloc_band_width,omitempty"`
	MaxConsecutiveLossPacketSum *uint32  `protobuf:"varint,9,req,name=max_consecutive_loss_packet_sum" json:"max_consecutive_loss_packet_sum,omitempty"`
	MaxUnorderedPacketSum       *uint32  `protobuf:"varint,10,req,name=max_unordered_packet_sum" json:"max_unordered_packet_sum,omitempty"`
	RttLevel                    *uint32  `protobuf:"varint,11,req,name=rtt_level" json:"rtt_level,omitempty"`
	LossRateLevel               *uint32  `protobuf:"varint,12,req,name=loss_rate_level" json:"loss_rate_level,omitempty"`
	StabilityFactor             *int32   `protobuf:"zigzag32,13,req,name=stability_factor" json:"stability_factor,omitempty"`
	Trend                       *uint32  `protobuf:"varint,14,req,name=trend" json:"trend,omitempty"`
	EnableFlag                  *int32   `protobuf:"zigzag32,15,req,name=enable_flag" json:"enable_flag,omitempty"`
	TickTime                    *uint64  `protobuf:"varint,16,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime                     *uint64  `protobuf:"varint,17,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *ProtoPhysicalLinkQuality) Reset()         { *m = ProtoPhysicalLinkQuality{} }
func (m *ProtoPhysicalLinkQuality) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkQuality) ProtoMessage()    {}
func (*ProtoPhysicalLinkQuality) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{1}
}
func (m *ProtoPhysicalLinkQuality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkQuality.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkQuality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkQuality.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkQuality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkQuality.Merge(dst, src)
}
func (m *ProtoPhysicalLinkQuality) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkQuality.Size(m)
}
func (m *ProtoPhysicalLinkQuality) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkQuality.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkQuality proto.InternalMessageInfo

func (m *ProtoPhysicalLinkQuality) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkQuality) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetRtt() uint32 {
	if m != nil && m.Rtt != nil {
		return *m.Rtt
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetLossRate() uint32 {
	if m != nil && m.LossRate != nil {
		return *m.LossRate
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetJitter() uint32 {
	if m != nil && m.Jitter != nil {
		return *m.Jitter
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetBandWidth() uint32 {
	if m != nil && m.BandWidth != nil {
		return *m.BandWidth
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetAllocBandWidth() uint32 {
	if m != nil && m.AllocBandWidth != nil {
		return *m.AllocBandWidth
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetMaxConsecutiveLossPacketSum() uint32 {
	if m != nil && m.MaxConsecutiveLossPacketSum != nil {
		return *m.MaxConsecutiveLossPacketSum
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetMaxUnorderedPacketSum() uint32 {
	if m != nil && m.MaxUnorderedPacketSum != nil {
		return *m.MaxUnorderedPacketSum
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetRttLevel() uint32 {
	if m != nil && m.RttLevel != nil {
		return *m.RttLevel
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetLossRateLevel() uint32 {
	if m != nil && m.LossRateLevel != nil {
		return *m.LossRateLevel
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetStabilityFactor() int32 {
	if m != nil && m.StabilityFactor != nil {
		return *m.StabilityFactor
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetTrend() uint32 {
	if m != nil && m.Trend != nil {
		return *m.Trend
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetEnableFlag() int32 {
	if m != nil && m.EnableFlag != nil {
		return *m.EnableFlag
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// IP 列表
// @since 1.0
type ProtoNicList struct {
	Nic                  []*ProtoNicList_NicInfo `protobuf:"bytes,1,rep,name=nic" json:"nic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProtoNicList) Reset()         { *m = ProtoNicList{} }
func (m *ProtoNicList) String() string { return proto.CompactTextString(m) }
func (*ProtoNicList) ProtoMessage()    {}
func (*ProtoNicList) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{2}
}
func (m *ProtoNicList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoNicList.Unmarshal(m, b)
}
func (m *ProtoNicList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoNicList.Marshal(b, m, deterministic)
}
func (dst *ProtoNicList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoNicList.Merge(dst, src)
}
func (m *ProtoNicList) XXX_Size() int {
	return xxx_messageInfo_ProtoNicList.Size(m)
}
func (m *ProtoNicList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoNicList.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoNicList proto.InternalMessageInfo

func (m *ProtoNicList) GetNic() []*ProtoNicList_NicInfo {
	if m != nil {
		return m.Nic
	}
	return nil
}

type ProtoNicList_NicInfo struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Ip                   *string  `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoNicList_NicInfo) Reset()         { *m = ProtoNicList_NicInfo{} }
func (m *ProtoNicList_NicInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoNicList_NicInfo) ProtoMessage()    {}
func (*ProtoNicList_NicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{2, 0}
}
func (m *ProtoNicList_NicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoNicList_NicInfo.Unmarshal(m, b)
}
func (m *ProtoNicList_NicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoNicList_NicInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoNicList_NicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoNicList_NicInfo.Merge(dst, src)
}
func (m *ProtoNicList_NicInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoNicList_NicInfo.Size(m)
}
func (m *ProtoNicList_NicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoNicList_NicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoNicList_NicInfo proto.InternalMessageInfo

func (m *ProtoNicList_NicInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ProtoNicList_NicInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

// =============================================================================================================================
// 用户基础信息汇报
// @since 1.0
type ProtoUserInfo struct {
	UserId               *uint64  `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	UserType             *uint32  `protobuf:"varint,2,req,name=user_type" json:"user_type,omitempty"`
	DeviceType           *uint32  `protobuf:"varint,3,req,name=device_type" json:"device_type,omitempty"`
	Os                   *string  `protobuf:"bytes,4,req,name=os" json:"os,omitempty"`
	SoftwareVersion      *string  `protobuf:"bytes,5,req,name=software_version" json:"software_version,omitempty"`
	TickTime             *uint64  `protobuf:"varint,6,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime              *uint64  `protobuf:"varint,7,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoUserInfo) Reset()         { *m = ProtoUserInfo{} }
func (m *ProtoUserInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoUserInfo) ProtoMessage()    {}
func (*ProtoUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{3}
}
func (m *ProtoUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoUserInfo.Unmarshal(m, b)
}
func (m *ProtoUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoUserInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoUserInfo.Merge(dst, src)
}
func (m *ProtoUserInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoUserInfo.Size(m)
}
func (m *ProtoUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoUserInfo proto.InternalMessageInfo

func (m *ProtoUserInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ProtoUserInfo) GetUserType() uint32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

func (m *ProtoUserInfo) GetDeviceType() uint32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *ProtoUserInfo) GetOs() string {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return ""
}

func (m *ProtoUserInfo) GetSoftwareVersion() string {
	if m != nil && m.SoftwareVersion != nil {
		return *m.SoftwareVersion
	}
	return ""
}

func (m *ProtoUserInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoUserInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// @since 1.0
type ProtoEndPointAddress struct {
	Version              *ProtoEndPointAddress_IPVersion `protobuf:"varint,1,req,name=version,enum=redsdn.ProtoEndPointAddress_IPVersion,def=0" json:"version,omitempty"`
	Ip                   *string                         `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port                 *uint32                         `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProtoEndPointAddress) Reset()         { *m = ProtoEndPointAddress{} }
func (m *ProtoEndPointAddress) String() string { return proto.CompactTextString(m) }
func (*ProtoEndPointAddress) ProtoMessage()    {}
func (*ProtoEndPointAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{4}
}
func (m *ProtoEndPointAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEndPointAddress.Unmarshal(m, b)
}
func (m *ProtoEndPointAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEndPointAddress.Marshal(b, m, deterministic)
}
func (dst *ProtoEndPointAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEndPointAddress.Merge(dst, src)
}
func (m *ProtoEndPointAddress) XXX_Size() int {
	return xxx_messageInfo_ProtoEndPointAddress.Size(m)
}
func (m *ProtoEndPointAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEndPointAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEndPointAddress proto.InternalMessageInfo

const Default_ProtoEndPointAddress_Version ProtoEndPointAddress_IPVersion = ProtoEndPointAddress_V4

func (m *ProtoEndPointAddress) GetVersion() ProtoEndPointAddress_IPVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_ProtoEndPointAddress_Version
}

func (m *ProtoEndPointAddress) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ProtoEndPointAddress) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

// Relay 信息汇报
// @since 1.0
type ProtoRelayInfo struct {
	Index                      *uint32               `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	RelayName                  *string               `protobuf:"bytes,2,req,name=relay_name" json:"relay_name,omitempty"`
	IdcId                      *uint32               `protobuf:"varint,3,req,name=idc_id" json:"idc_id,omitempty"`
	Domain                     *string               `protobuf:"bytes,4,req,name=domain" json:"domain,omitempty"`
	DomainIndex                *uint32               `protobuf:"varint,5,req,name=domain_index" json:"domain_index,omitempty"`
	Isp                        *string               `protobuf:"bytes,6,req,name=isp" json:"isp,omitempty"`
	IspIndex                   *uint32               `protobuf:"varint,7,req,name=isp_index" json:"isp_index,omitempty"`
	MediaAddress               *ProtoEndPointAddress `protobuf:"bytes,8,req,name=media_address" json:"media_address,omitempty"`
	MulticastSelectPathAddress *ProtoEndPointAddress `protobuf:"bytes,9,req,name=multicast_select_path_address" json:"multicast_select_path_address,omitempty"`
	IperfAddress               *ProtoEndPointAddress `protobuf:"bytes,10,req,name=iperf_address" json:"iperf_address,omitempty"`
	RatedOutboundBandwidth     *uint32               `protobuf:"varint,11,req,name=rated_outbound_bandwidth" json:"rated_outbound_bandwidth,omitempty"`
	RatedInboundBandwidth      *uint32               `protobuf:"varint,12,req,name=rated_inbound_bandwidth" json:"rated_inbound_bandwidth,omitempty"`
	RatedMaxConnections        *uint32               `protobuf:"varint,13,req,name=rated_max_connections" json:"rated_max_connections,omitempty"`
	RatedMaxSessions           *uint32               `protobuf:"varint,14,req,name=rated_max_sessions" json:"rated_max_sessions,omitempty"`
	RatedCost                  *uint32               `protobuf:"varint,15,req,name=rated_cost" json:"rated_cost,omitempty"`
	DetectionNum               *uint32               `protobuf:"varint,16,req,name=detection_num" json:"detection_num,omitempty"`
	TickTime                   *uint64               `protobuf:"varint,17,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime                    *uint64               `protobuf:"varint,18,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}              `json:"-"`
	XXX_unrecognized           []byte                `json:"-"`
	XXX_sizecache              int32                 `json:"-"`
}

func (m *ProtoRelayInfo) Reset()         { *m = ProtoRelayInfo{} }
func (m *ProtoRelayInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoRelayInfo) ProtoMessage()    {}
func (*ProtoRelayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{5}
}
func (m *ProtoRelayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRelayInfo.Unmarshal(m, b)
}
func (m *ProtoRelayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRelayInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoRelayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRelayInfo.Merge(dst, src)
}
func (m *ProtoRelayInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoRelayInfo.Size(m)
}
func (m *ProtoRelayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRelayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRelayInfo proto.InternalMessageInfo

func (m *ProtoRelayInfo) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoRelayInfo) GetRelayName() string {
	if m != nil && m.RelayName != nil {
		return *m.RelayName
	}
	return ""
}

func (m *ProtoRelayInfo) GetIdcId() uint32 {
	if m != nil && m.IdcId != nil {
		return *m.IdcId
	}
	return 0
}

func (m *ProtoRelayInfo) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *ProtoRelayInfo) GetDomainIndex() uint32 {
	if m != nil && m.DomainIndex != nil {
		return *m.DomainIndex
	}
	return 0
}

func (m *ProtoRelayInfo) GetIsp() string {
	if m != nil && m.Isp != nil {
		return *m.Isp
	}
	return ""
}

func (m *ProtoRelayInfo) GetIspIndex() uint32 {
	if m != nil && m.IspIndex != nil {
		return *m.IspIndex
	}
	return 0
}

func (m *ProtoRelayInfo) GetMediaAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.MediaAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetMulticastSelectPathAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.MulticastSelectPathAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetIperfAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.IperfAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetRatedOutboundBandwidth() uint32 {
	if m != nil && m.RatedOutboundBandwidth != nil {
		return *m.RatedOutboundBandwidth
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedInboundBandwidth() uint32 {
	if m != nil && m.RatedInboundBandwidth != nil {
		return *m.RatedInboundBandwidth
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedMaxConnections() uint32 {
	if m != nil && m.RatedMaxConnections != nil {
		return *m.RatedMaxConnections
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedMaxSessions() uint32 {
	if m != nil && m.RatedMaxSessions != nil {
		return *m.RatedMaxSessions
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedCost() uint32 {
	if m != nil && m.RatedCost != nil {
		return *m.RatedCost
	}
	return 0
}

func (m *ProtoRelayInfo) GetDetectionNum() uint32 {
	if m != nil && m.DetectionNum != nil {
		return *m.DetectionNum
	}
	return 0
}

func (m *ProtoRelayInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoRelayInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// @since 1.0
type ProtoMulticastLinkInfo struct {
	NodeId               *uint32                          `protobuf:"varint,1,req,name=node_id" json:"node_id,omitempty"`
	NodeType             *ProtoMulticastLinkInfo_NodeType `protobuf:"varint,2,req,name=node_type,enum=redsdn.ProtoMulticastLinkInfo_NodeType" json:"node_type,omitempty"`
	RoleType             *uint32                          `protobuf:"varint,3,req,name=role_type" json:"role_type,omitempty"`
	PhysicalLinkId       *string                          `protobuf:"bytes,4,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	LogicalLinkId        *uint32                          `protobuf:"varint,5,req,name=logical_link_id" json:"logical_link_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ProtoMulticastLinkInfo) Reset()         { *m = ProtoMulticastLinkInfo{} }
func (m *ProtoMulticastLinkInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoMulticastLinkInfo) ProtoMessage()    {}
func (*ProtoMulticastLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{6}
}
func (m *ProtoMulticastLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMulticastLinkInfo.Unmarshal(m, b)
}
func (m *ProtoMulticastLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMulticastLinkInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoMulticastLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMulticastLinkInfo.Merge(dst, src)
}
func (m *ProtoMulticastLinkInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoMulticastLinkInfo.Size(m)
}
func (m *ProtoMulticastLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMulticastLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMulticastLinkInfo proto.InternalMessageInfo

func (m *ProtoMulticastLinkInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastLinkInfo) GetNodeType() ProtoMulticastLinkInfo_NodeType {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return ProtoMulticastLinkInfo_USER
}

func (m *ProtoMulticastLinkInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoMulticastLinkInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoMulticastLinkInfo) GetLogicalLinkId() uint32 {
	if m != nil && m.LogicalLinkId != nil {
		return *m.LogicalLinkId
	}
	return 0
}

// 组播信息汇报
// @since 1.0
type ProtoMulticastInfo struct {
	MulticastId               *uint64                           `protobuf:"varint,1,req,name=multicast_id" json:"multicast_id,omitempty"`
	RoleType                  *uint32                           `protobuf:"varint,2,req,name=role_type" json:"role_type,omitempty"`
	NodeId                    *uint32                           `protobuf:"varint,3,req,name=node_id" json:"node_id,omitempty"`
	NodeType                  *uint32                           `protobuf:"varint,4,req,name=node_type" json:"node_type,omitempty"`
	MulticastPublishVersion   *uint32                           `protobuf:"varint,5,opt,name=multicast_publish_version" json:"multicast_publish_version,omitempty"`
	MulticastSubscribeVersion *uint32                           `protobuf:"varint,6,opt,name=multicast_subscribe_version" json:"multicast_subscribe_version,omitempty"`
	Parents                   []*ProtoMulticastLinkInfo         `protobuf:"bytes,7,rep,name=parents" json:"parents,omitempty"`
	Children                  []*ProtoMulticastLinkInfo         `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
	OperationType             *ProtoMulticastInfo_OperationType `protobuf:"varint,9,req,name=operation_type,enum=redsdn.ProtoMulticastInfo_OperationType" json:"operation_type,omitempty"`
	TickTime                  *uint64                           `protobuf:"varint,10,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime                   *uint64                           `protobuf:"varint,11,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                          `json:"-"`
	XXX_unrecognized          []byte                            `json:"-"`
	XXX_sizecache             int32                             `json:"-"`
}

func (m *ProtoMulticastInfo) Reset()         { *m = ProtoMulticastInfo{} }
func (m *ProtoMulticastInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoMulticastInfo) ProtoMessage()    {}
func (*ProtoMulticastInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{7}
}
func (m *ProtoMulticastInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMulticastInfo.Unmarshal(m, b)
}
func (m *ProtoMulticastInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMulticastInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoMulticastInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMulticastInfo.Merge(dst, src)
}
func (m *ProtoMulticastInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoMulticastInfo.Size(m)
}
func (m *ProtoMulticastInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMulticastInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMulticastInfo proto.InternalMessageInfo

func (m *ProtoMulticastInfo) GetMulticastId() uint64 {
	if m != nil && m.MulticastId != nil {
		return *m.MulticastId
	}
	return 0
}

func (m *ProtoMulticastInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoMulticastInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastInfo) GetNodeType() uint32 {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return 0
}

func (m *ProtoMulticastInfo) GetMulticastPublishVersion() uint32 {
	if m != nil && m.MulticastPublishVersion != nil {
		return *m.MulticastPublishVersion
	}
	return 0
}

func (m *ProtoMulticastInfo) GetMulticastSubscribeVersion() uint32 {
	if m != nil && m.MulticastSubscribeVersion != nil {
		return *m.MulticastSubscribeVersion
	}
	return 0
}

func (m *ProtoMulticastInfo) GetParents() []*ProtoMulticastLinkInfo {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ProtoMulticastInfo) GetChildren() []*ProtoMulticastLinkInfo {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ProtoMulticastInfo) GetOperationType() ProtoMulticastInfo_OperationType {
	if m != nil && m.OperationType != nil {
		return *m.OperationType
	}
	return ProtoMulticastInfo_ADD
}

func (m *ProtoMulticastInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoMulticastInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// 组播事件汇报
// @since 1.0
type ProtoMulticastEventInfo struct {
	MulticastId          *uint64                          `protobuf:"varint,1,req,name=multicast_id" json:"multicast_id,omitempty"`
	EventKey             *string                          `protobuf:"bytes,2,req,name=event_key" json:"event_key,omitempty"`
	EventType            *int32                           `protobuf:"varint,3,req,name=event_type" json:"event_type,omitempty"`
	EventInfo            *string                          `protobuf:"bytes,4,req,name=event_info" json:"event_info,omitempty"`
	NodeId               *uint32                          `protobuf:"varint,5,req,name=node_id" json:"node_id,omitempty"`
	NodeType             *ProtoMulticastLinkInfo_NodeType `protobuf:"varint,6,req,name=node_type,enum=redsdn.ProtoMulticastLinkInfo_NodeType" json:"node_type,omitempty"`
	PhysicalLinkId       *string                          `protobuf:"bytes,7,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	LogicalLinkId        *uint32                          `protobuf:"varint,8,req,name=logical_link_id" json:"logical_link_id,omitempty"`
	TickTime             *uint64                          `protobuf:"varint,9,req,name=tick_time" json:"tick_time,omitempty"`
	UtcTime              *uint64                          `protobuf:"varint,10,req,name=utc_time" json:"utc_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ProtoMulticastEventInfo) Reset()         { *m = ProtoMulticastEventInfo{} }
func (m *ProtoMulticastEventInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoMulticastEventInfo) ProtoMessage()    {}
func (*ProtoMulticastEventInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{8}
}
func (m *ProtoMulticastEventInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMulticastEventInfo.Unmarshal(m, b)
}
func (m *ProtoMulticastEventInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMulticastEventInfo.Marshal(b, m, deterministic)
}
func (dst *ProtoMulticastEventInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMulticastEventInfo.Merge(dst, src)
}
func (m *ProtoMulticastEventInfo) XXX_Size() int {
	return xxx_messageInfo_ProtoMulticastEventInfo.Size(m)
}
func (m *ProtoMulticastEventInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMulticastEventInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMulticastEventInfo proto.InternalMessageInfo

func (m *ProtoMulticastEventInfo) GetMulticastId() uint64 {
	if m != nil && m.MulticastId != nil {
		return *m.MulticastId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetEventKey() string {
	if m != nil && m.EventKey != nil {
		return *m.EventKey
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetEventInfo() string {
	if m != nil && m.EventInfo != nil {
		return *m.EventInfo
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetNodeType() ProtoMulticastLinkInfo_NodeType {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return ProtoMulticastLinkInfo_USER
}

func (m *ProtoMulticastEventInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetLogicalLinkId() uint32 {
	if m != nil && m.LogicalLinkId != nil {
		return *m.LogicalLinkId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// StatItemValue 统计数据定义
// @since 2.0
// @date 2018/2/1
type ProtoStatItemValue struct {
	ObjKey               *ProtoStatItemValue_ProtoStatObjKey  `protobuf:"bytes,1,req,name=obj_key" json:"obj_key,omitempty"`
	DataValues           []*ProtoStatItemValue_ProtoDataValue `protobuf:"bytes,2,rep,name=data_values" json:"data_values,omitempty"`
	StatInterval         *uint32                              `protobuf:"varint,3,req,name=stat_interval" json:"stat_interval,omitempty"`
	SubStatInterval      *uint32                              `protobuf:"varint,4,req,name=sub_stat_interval" json:"sub_stat_interval,omitempty"`
	Timestamp            *uint64                              `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ProtoStatItemValue) Reset()         { *m = ProtoStatItemValue{} }
func (m *ProtoStatItemValue) String() string { return proto.CompactTextString(m) }
func (*ProtoStatItemValue) ProtoMessage()    {}
func (*ProtoStatItemValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{9}
}
func (m *ProtoStatItemValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStatItemValue.Unmarshal(m, b)
}
func (m *ProtoStatItemValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStatItemValue.Marshal(b, m, deterministic)
}
func (dst *ProtoStatItemValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStatItemValue.Merge(dst, src)
}
func (m *ProtoStatItemValue) XXX_Size() int {
	return xxx_messageInfo_ProtoStatItemValue.Size(m)
}
func (m *ProtoStatItemValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStatItemValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStatItemValue proto.InternalMessageInfo

func (m *ProtoStatItemValue) GetObjKey() *ProtoStatItemValue_ProtoStatObjKey {
	if m != nil {
		return m.ObjKey
	}
	return nil
}

func (m *ProtoStatItemValue) GetDataValues() []*ProtoStatItemValue_ProtoDataValue {
	if m != nil {
		return m.DataValues
	}
	return nil
}

func (m *ProtoStatItemValue) GetStatInterval() uint32 {
	if m != nil && m.StatInterval != nil {
		return *m.StatInterval
	}
	return 0
}

func (m *ProtoStatItemValue) GetSubStatInterval() uint32 {
	if m != nil && m.SubStatInterval != nil {
		return *m.SubStatInterval
	}
	return 0
}

func (m *ProtoStatItemValue) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ProtoStatItemValue_ProtoDataValue struct {
	Index                *uint32                                               `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Sum                  *uint32                                               `protobuf:"varint,2,req,name=sum" json:"sum,omitempty"`
	Size                 *uint32                                               `protobuf:"varint,3,req,name=size" json:"size,omitempty"`
	BitmapValues         []*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue `protobuf:"bytes,4,rep,name=bitmap_values" json:"bitmap_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *ProtoStatItemValue_ProtoDataValue) Reset()         { *m = ProtoStatItemValue_ProtoDataValue{} }
func (m *ProtoStatItemValue_ProtoDataValue) String() string { return proto.CompactTextString(m) }
func (*ProtoStatItemValue_ProtoDataValue) ProtoMessage()    {}
func (*ProtoStatItemValue_ProtoDataValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{9, 0}
}
func (m *ProtoStatItemValue_ProtoDataValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue.Unmarshal(m, b)
}
func (m *ProtoStatItemValue_ProtoDataValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue.Marshal(b, m, deterministic)
}
func (dst *ProtoStatItemValue_ProtoDataValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStatItemValue_ProtoDataValue.Merge(dst, src)
}
func (m *ProtoStatItemValue_ProtoDataValue) XXX_Size() int {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue.Size(m)
}
func (m *ProtoStatItemValue_ProtoDataValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStatItemValue_ProtoDataValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStatItemValue_ProtoDataValue proto.InternalMessageInfo

func (m *ProtoStatItemValue_ProtoDataValue) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetSum() uint32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetBitmapValues() []*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue {
	if m != nil {
		return m.BitmapValues
	}
	return nil
}

type ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue struct {
	Index                *uint32  `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	BitMap               *uint64  `protobuf:"varint,2,req,name=bit_map" json:"bit_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) Reset() {
	*m = ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue{}
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) ProtoMessage() {}
func (*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{9, 0, 0}
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue.Unmarshal(m, b)
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue.Marshal(b, m, deterministic)
}
func (dst *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue.Merge(dst, src)
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) XXX_Size() int {
	return xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue.Size(m)
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue proto.InternalMessageInfo

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) GetBitMap() uint64 {
	if m != nil && m.BitMap != nil {
		return *m.BitMap
	}
	return 0
}

type ProtoStatItemValue_ProtoStatObjKey struct {
	Self                 *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj   `protobuf:"bytes,1,req,name=self" json:"self,omitempty"`
	Associates           []*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj `protobuf:"bytes,2,rep,name=associates" json:"associates,omitempty"`
	StatType             *uint32                                            `protobuf:"varint,3,req,name=stat_type" json:"stat_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *ProtoStatItemValue_ProtoStatObjKey) Reset()         { *m = ProtoStatItemValue_ProtoStatObjKey{} }
func (m *ProtoStatItemValue_ProtoStatObjKey) String() string { return proto.CompactTextString(m) }
func (*ProtoStatItemValue_ProtoStatObjKey) ProtoMessage()    {}
func (*ProtoStatItemValue_ProtoStatObjKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{9, 1}
}
func (m *ProtoStatItemValue_ProtoStatObjKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey.Unmarshal(m, b)
}
func (m *ProtoStatItemValue_ProtoStatObjKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey.Marshal(b, m, deterministic)
}
func (dst *ProtoStatItemValue_ProtoStatObjKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey.Merge(dst, src)
}
func (m *ProtoStatItemValue_ProtoStatObjKey) XXX_Size() int {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey.Size(m)
}
func (m *ProtoStatItemValue_ProtoStatObjKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey proto.InternalMessageInfo

func (m *ProtoStatItemValue_ProtoStatObjKey) GetSelf() *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *ProtoStatItemValue_ProtoStatObjKey) GetAssociates() []*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj {
	if m != nil {
		return m.Associates
	}
	return nil
}

func (m *ProtoStatItemValue_ProtoStatObjKey) GetStatType() uint32 {
	if m != nil && m.StatType != nil {
		return *m.StatType
	}
	return 0
}

type ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj struct {
	ObjId                *string  `protobuf:"bytes,1,req,name=obj_id" json:"obj_id,omitempty"`
	ObjType              *uint32  `protobuf:"varint,2,req,name=obj_type" json:"obj_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) Reset() {
	*m = ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj{}
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) ProtoMessage() {}
func (*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{9, 1, 0}
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj.Unmarshal(m, b)
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj.Marshal(b, m, deterministic)
}
func (dst *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj.Merge(dst, src)
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) XXX_Size() int {
	return xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj.Size(m)
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj proto.InternalMessageInfo

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) GetObjId() string {
	if m != nil && m.ObjId != nil {
		return *m.ObjId
	}
	return ""
}

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) GetObjType() uint32 {
	if m != nil && m.ObjType != nil {
		return *m.ObjType
	}
	return 0
}

// =============================================================================================================================
// 物理链路状态变化事件值定义
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkChangeNotify struct {
	PhysicalLinkId       *string                                          `protobuf:"bytes,1,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	OldState             *ProtoPhysicalLinkChangeNotify_PhysicalLinkState `protobuf:"varint,2,req,name=old_state,enum=redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState" json:"old_state,omitempty"`
	NewState             *ProtoPhysicalLinkChangeNotify_PhysicalLinkState `protobuf:"varint,3,req,name=new_state,enum=redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState" json:"new_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *ProtoPhysicalLinkChangeNotify) Reset()         { *m = ProtoPhysicalLinkChangeNotify{} }
func (m *ProtoPhysicalLinkChangeNotify) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkChangeNotify) ProtoMessage()    {}
func (*ProtoPhysicalLinkChangeNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{10}
}
func (m *ProtoPhysicalLinkChangeNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkChangeNotify.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkChangeNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkChangeNotify.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkChangeNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkChangeNotify.Merge(dst, src)
}
func (m *ProtoPhysicalLinkChangeNotify) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkChangeNotify.Size(m)
}
func (m *ProtoPhysicalLinkChangeNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkChangeNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkChangeNotify proto.InternalMessageInfo

func (m *ProtoPhysicalLinkChangeNotify) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkChangeNotify) GetOldState() ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	if m != nil && m.OldState != nil {
		return *m.OldState
	}
	return ProtoPhysicalLinkChangeNotify_ONLINE
}

func (m *ProtoPhysicalLinkChangeNotify) GetNewState() ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	if m != nil && m.NewState != nil {
		return *m.NewState
	}
	return ProtoPhysicalLinkChangeNotify_ONLINE
}

// =============================================================================================================================
// 物理链路销毁事件值定义
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkDestroyNotify struct {
	PhysicalLinkId       *string  `protobuf:"bytes,1,req,name=physical_link_id" json:"physical_link_id,omitempty"`
	Direction            *uint32  `protobuf:"varint,2,req,name=direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoPhysicalLinkDestroyNotify) Reset()         { *m = ProtoPhysicalLinkDestroyNotify{} }
func (m *ProtoPhysicalLinkDestroyNotify) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkDestroyNotify) ProtoMessage()    {}
func (*ProtoPhysicalLinkDestroyNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{11}
}
func (m *ProtoPhysicalLinkDestroyNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkDestroyNotify.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkDestroyNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkDestroyNotify.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkDestroyNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkDestroyNotify.Merge(dst, src)
}
func (m *ProtoPhysicalLinkDestroyNotify) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkDestroyNotify.Size(m)
}
func (m *ProtoPhysicalLinkDestroyNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkDestroyNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkDestroyNotify proto.InternalMessageInfo

func (m *ProtoPhysicalLinkDestroyNotify) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkDestroyNotify) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

// =============================================================================================================================
// 物理链路事件汇报指令格式
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkEvent struct {
	OwnerId   *uint32 `protobuf:"varint,1,req,name=owner_id" json:"owner_id,omitempty"`
	OwnerType *uint32 `protobuf:"varint,2,req,name=owner_type" json:"owner_type,omitempty"`
	EventType *uint32 `protobuf:"varint,3,req,name=event_type" json:"event_type,omitempty"`
	// 			2   被动方创建物理链路成功
	// 			3   主动方关闭物理链路
	// 			4   被动方关闭物理链路
	// 			5   主动方物理链路状态变化
	// 			6   被动方物理链路状态变化
	// 			7   传输控制计算链路质量
	// 			8   传输控制负载均衡后质量
	// 			101 仿真机链路配置信息信息
	BasicInfo            *ProtoPhysicalLinkInfo          `protobuf:"bytes,4,opt,name=basic_info" json:"basic_info,omitempty"`
	ChangeNotify         *ProtoPhysicalLinkChangeNotify  `protobuf:"bytes,5,opt,name=change_notify" json:"change_notify,omitempty"`
	DestroyNotify        *ProtoPhysicalLinkDestroyNotify `protobuf:"bytes,6,opt,name=destroy_notify" json:"destroy_notify,omitempty"`
	LinkQuality          *ProtoPhysicalLinkQuality       `protobuf:"bytes,7,opt,name=link_quality" json:"link_quality,omitempty"`
	Timestamp            *uint64                         `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProtoPhysicalLinkEvent) Reset()         { *m = ProtoPhysicalLinkEvent{} }
func (m *ProtoPhysicalLinkEvent) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkEvent) ProtoMessage()    {}
func (*ProtoPhysicalLinkEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{12}
}
func (m *ProtoPhysicalLinkEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkEvent.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkEvent.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkEvent.Merge(dst, src)
}
func (m *ProtoPhysicalLinkEvent) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkEvent.Size(m)
}
func (m *ProtoPhysicalLinkEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkEvent proto.InternalMessageInfo

func (m *ProtoPhysicalLinkEvent) GetOwnerId() uint32 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetOwnerType() uint32 {
	if m != nil && m.OwnerType != nil {
		return *m.OwnerType
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetEventType() uint32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetBasicInfo() *ProtoPhysicalLinkInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetChangeNotify() *ProtoPhysicalLinkChangeNotify {
	if m != nil {
		return m.ChangeNotify
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetDestroyNotify() *ProtoPhysicalLinkDestroyNotify {
	if m != nil {
		return m.DestroyNotify
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetLinkQuality() *ProtoPhysicalLinkQuality {
	if m != nil {
		return m.LinkQuality
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// =============================================================================================================================
// 物理链路统计数据汇报格式
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkStatData struct {
	OwnerId              *uint32             `protobuf:"varint,1,req,name=owner_id" json:"owner_id,omitempty"`
	OwnerType            *uint32             `protobuf:"varint,2,req,name=owner_type" json:"owner_type,omitempty"`
	ItemValue            *ProtoStatItemValue `protobuf:"bytes,3,req,name=item_value" json:"item_value,omitempty"`
	Timestamp            *uint64             `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoPhysicalLinkStatData) Reset()         { *m = ProtoPhysicalLinkStatData{} }
func (m *ProtoPhysicalLinkStatData) String() string { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkStatData) ProtoMessage()    {}
func (*ProtoPhysicalLinkStatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{13}
}
func (m *ProtoPhysicalLinkStatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPhysicalLinkStatData.Unmarshal(m, b)
}
func (m *ProtoPhysicalLinkStatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPhysicalLinkStatData.Marshal(b, m, deterministic)
}
func (dst *ProtoPhysicalLinkStatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPhysicalLinkStatData.Merge(dst, src)
}
func (m *ProtoPhysicalLinkStatData) XXX_Size() int {
	return xxx_messageInfo_ProtoPhysicalLinkStatData.Size(m)
}
func (m *ProtoPhysicalLinkStatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPhysicalLinkStatData.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPhysicalLinkStatData proto.InternalMessageInfo

func (m *ProtoPhysicalLinkStatData) GetOwnerId() uint32 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *ProtoPhysicalLinkStatData) GetOwnerType() uint32 {
	if m != nil && m.OwnerType != nil {
		return *m.OwnerType
	}
	return 0
}

func (m *ProtoPhysicalLinkStatData) GetItemValue() *ProtoStatItemValue {
	if m != nil {
		return m.ItemValue
	}
	return nil
}

func (m *ProtoPhysicalLinkStatData) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// =============================================================================================================================
// 日志文件的数据编码结构
// @since 1.0
type ProtoMessage struct {
	UserInfo             *ProtoUserInfo             `protobuf:"bytes,1,opt,name=user_info" json:"user_info,omitempty"`
	RelayInfo            *ProtoRelayInfo            `protobuf:"bytes,2,opt,name=relay_info" json:"relay_info,omitempty"`
	MulticastInfo        *ProtoMulticastInfo        `protobuf:"bytes,3,opt,name=multicast_info" json:"multicast_info,omitempty"`
	MulticastEventInfo   *ProtoMulticastEventInfo   `protobuf:"bytes,4,opt,name=multicast_event_info" json:"multicast_event_info,omitempty"`
	NicList              *ProtoNicList              `protobuf:"bytes,5,opt,name=nic_list" json:"nic_list,omitempty"`
	LinkEvent            *ProtoPhysicalLinkEvent    `protobuf:"bytes,6,opt,name=link_event" json:"link_event,omitempty"`
	StatData             *ProtoPhysicalLinkStatData `protobuf:"bytes,7,opt,name=stat_data" json:"stat_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ProtoMessage) Reset()         { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()    {}
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{14}
}
func (m *ProtoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMessage.Unmarshal(m, b)
}
func (m *ProtoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMessage.Marshal(b, m, deterministic)
}
func (dst *ProtoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMessage.Merge(dst, src)
}
func (m *ProtoMessage) XXX_Size() int {
	return xxx_messageInfo_ProtoMessage.Size(m)
}
func (m *ProtoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMessage proto.InternalMessageInfo

func (m *ProtoMessage) GetUserInfo() *ProtoUserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *ProtoMessage) GetRelayInfo() *ProtoRelayInfo {
	if m != nil {
		return m.RelayInfo
	}
	return nil
}

func (m *ProtoMessage) GetMulticastInfo() *ProtoMulticastInfo {
	if m != nil {
		return m.MulticastInfo
	}
	return nil
}

func (m *ProtoMessage) GetMulticastEventInfo() *ProtoMulticastEventInfo {
	if m != nil {
		return m.MulticastEventInfo
	}
	return nil
}

func (m *ProtoMessage) GetNicList() *ProtoNicList {
	if m != nil {
		return m.NicList
	}
	return nil
}

func (m *ProtoMessage) GetLinkEvent() *ProtoPhysicalLinkEvent {
	if m != nil {
		return m.LinkEvent
	}
	return nil
}

func (m *ProtoMessage) GetStatData() *ProtoPhysicalLinkStatData {
	if m != nil {
		return m.StatData
	}
	return nil
}

// =============================================================================================================================
// 实时数据传输结构
type ProtoMonitorMessage struct {
	Type                 *ProtoMonitorMessage_MessageType `protobuf:"varint,1,req,name=type,enum=redsdn.ProtoMonitorMessage_MessageType" json:"type,omitempty"`
	CommandId            *string                          `protobuf:"bytes,2,req,name=command_id" json:"command_id,omitempty"`
	Msg                  [][]byte                         `protobuf:"bytes,3,rep,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ProtoMonitorMessage) Reset()         { *m = ProtoMonitorMessage{} }
func (m *ProtoMonitorMessage) String() string { return proto.CompactTextString(m) }
func (*ProtoMonitorMessage) ProtoMessage()    {}
func (*ProtoMonitorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_redsdn_be1cf08a89234a05, []int{15}
}
func (m *ProtoMonitorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMonitorMessage.Unmarshal(m, b)
}
func (m *ProtoMonitorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMonitorMessage.Marshal(b, m, deterministic)
}
func (dst *ProtoMonitorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMonitorMessage.Merge(dst, src)
}
func (m *ProtoMonitorMessage) XXX_Size() int {
	return xxx_messageInfo_ProtoMonitorMessage.Size(m)
}
func (m *ProtoMonitorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMonitorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMonitorMessage proto.InternalMessageInfo

func (m *ProtoMonitorMessage) GetType() ProtoMonitorMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProtoMonitorMessage_USER_INFO
}

func (m *ProtoMonitorMessage) GetCommandId() string {
	if m != nil && m.CommandId != nil {
		return *m.CommandId
	}
	return ""
}

func (m *ProtoMonitorMessage) GetMsg() [][]byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoPhysicalLinkInfo)(nil), "redsdn.ProtoPhysicalLinkInfo")
	proto.RegisterType((*ProtoPhysicalLinkQuality)(nil), "redsdn.ProtoPhysicalLinkQuality")
	proto.RegisterType((*ProtoNicList)(nil), "redsdn.ProtoNicList")
	proto.RegisterType((*ProtoNicList_NicInfo)(nil), "redsdn.ProtoNicList.NicInfo")
	proto.RegisterType((*ProtoUserInfo)(nil), "redsdn.ProtoUserInfo")
	proto.RegisterType((*ProtoEndPointAddress)(nil), "redsdn.ProtoEndPointAddress")
	proto.RegisterType((*ProtoRelayInfo)(nil), "redsdn.ProtoRelayInfo")
	proto.RegisterType((*ProtoMulticastLinkInfo)(nil), "redsdn.ProtoMulticastLinkInfo")
	proto.RegisterType((*ProtoMulticastInfo)(nil), "redsdn.ProtoMulticastInfo")
	proto.RegisterType((*ProtoMulticastEventInfo)(nil), "redsdn.ProtoMulticastEventInfo")
	proto.RegisterType((*ProtoStatItemValue)(nil), "redsdn.ProtoStatItemValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoDataValue)(nil), "redsdn.ProtoStatItemValue.ProtoDataValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue)(nil), "redsdn.ProtoStatItemValue.ProtoDataValue.ProtoBitmapValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoStatObjKey)(nil), "redsdn.ProtoStatItemValue.ProtoStatObjKey")
	proto.RegisterType((*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj)(nil), "redsdn.ProtoStatItemValue.ProtoStatObjKey.ProtoStatObj")
	proto.RegisterType((*ProtoPhysicalLinkChangeNotify)(nil), "redsdn.ProtoPhysicalLinkChangeNotify")
	proto.RegisterType((*ProtoPhysicalLinkDestroyNotify)(nil), "redsdn.ProtoPhysicalLinkDestroyNotify")
	proto.RegisterType((*ProtoPhysicalLinkEvent)(nil), "redsdn.ProtoPhysicalLinkEvent")
	proto.RegisterType((*ProtoPhysicalLinkStatData)(nil), "redsdn.ProtoPhysicalLinkStatData")
	proto.RegisterType((*ProtoMessage)(nil), "redsdn.ProtoMessage")
	proto.RegisterType((*ProtoMonitorMessage)(nil), "redsdn.ProtoMonitorMessage")
	proto.RegisterEnum("redsdn.ProtoEndPointAddress_IPVersion", ProtoEndPointAddress_IPVersion_name, ProtoEndPointAddress_IPVersion_value)
	proto.RegisterEnum("redsdn.ProtoMulticastLinkInfo_NodeType", ProtoMulticastLinkInfo_NodeType_name, ProtoMulticastLinkInfo_NodeType_value)
	proto.RegisterEnum("redsdn.ProtoMulticastInfo_OperationType", ProtoMulticastInfo_OperationType_name, ProtoMulticastInfo_OperationType_value)
	proto.RegisterEnum("redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState", ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name, ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value)
	proto.RegisterEnum("redsdn.ProtoMonitorMessage_MessageType", ProtoMonitorMessage_MessageType_name, ProtoMonitorMessage_MessageType_value)
}

func init() { proto.RegisterFile("redsdn.proto", fileDescriptor_redsdn_be1cf08a89234a05) }

var fileDescriptor_redsdn_be1cf08a89234a05 = []byte{
	// 1774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x6f, 0x1b, 0x59,
	0x15, 0xcf, 0x8c, 0xbf, 0x8f, 0x3d, 0xce, 0xe4, 0x36, 0x69, 0xa6, 0x29, 0x6d, 0x5d, 0x03, 0x5d,
	0xef, 0x3e, 0x84, 0xc5, 0x5b, 0x16, 0xa9, 0x0b, 0x2b, 0x4c, 0xe2, 0x68, 0x4d, 0x1d, 0x27, 0xdb,
	0xa4, 0x91, 0x2a, 0x21, 0x8d, 0xae, 0x67, 0x6e, 0x92, 0xdb, 0xcc, 0x87, 0x99, 0x7b, 0x9d, 0x36,
	0x3c, 0x23, 0x90, 0x10, 0x82, 0x07, 0x9e, 0x78, 0xe1, 0x7f, 0xe1, 0x1d, 0xf1, 0xc0, 0x7f, 0x01,
	0x7f, 0x05, 0xba, 0x67, 0x66, 0x3c, 0x1e, 0x3b, 0x6e, 0x03, 0x3c, 0xd9, 0x73, 0xbe, 0xee, 0xf9,
	0xf8, 0x9d, 0x73, 0xee, 0x85, 0x46, 0xc4, 0x5c, 0xe1, 0x06, 0xbb, 0x93, 0x28, 0x94, 0x21, 0x29,
	0xc7, 0x5f, 0xed, 0x7f, 0x6a, 0xb0, 0x75, 0xac, 0x28, 0xc7, 0x97, 0x37, 0x82, 0x3b, 0xd4, 0x1b,
	0xf2, 0xe0, 0x6a, 0x10, 0x9c, 0x87, 0xc4, 0x02, 0x73, 0x92, 0xd0, 0x6c, 0x8f, 0x07, 0x57, 0x36,
	0x77, 0x2d, 0xad, 0xa5, 0x77, 0x6a, 0x64, 0x03, 0x6a, 0x2e, 0x8f, 0x98, 0x23, 0x79, 0x18, 0x58,
	0x7a, 0x4b, 0xef, 0x18, 0xe4, 0x3e, 0x34, 0xbd, 0x50, 0x49, 0x06, 0x4c, 0xda, 0xf2, 0x66, 0xc2,
	0xac, 0x02, 0xd2, 0x09, 0x40, 0x4c, 0xa7, 0xae, 0x1b, 0x59, 0x45, 0x54, 0xdf, 0x02, 0xc3, 0x65,
	0x42, 0x66, 0xa2, 0x25, 0x14, 0x55, 0x56, 0x15, 0x19, 0x25, 0xcb, 0xe9, 0x41, 0x51, 0xe8, 0xb1,
	0x58, 0xaa, 0x92, 0x4a, 0x49, 0xee, 0x5c, 0xd9, 0x92, 0xfb, 0xcc, 0xaa, 0xb6, 0xf4, 0x4e, 0x91,
	0x98, 0x50, 0x9d, 0x4a, 0x27, 0xa6, 0xd4, 0x14, 0xa5, 0xfd, 0x87, 0x02, 0x58, 0x4b, 0x41, 0x7d,
	0x3b, 0xa5, 0x1e, 0x97, 0x37, 0x1f, 0x88, 0xab, 0x0e, 0x05, 0xee, 0xbe, 0xb7, 0xf4, 0x96, 0xd6,
	0x31, 0xd4, 0x47, 0x24, 0x65, 0x12, 0xc6, 0x06, 0xd4, 0xbc, 0x50, 0x08, 0x3b, 0xa2, 0x92, 0x61,
	0x14, 0x06, 0x69, 0x42, 0xf9, 0x2d, 0x97, 0x92, 0x45, 0x73, 0xee, 0xcf, 0x92, 0x52, 0x4e, 0x83,
	0x1f, 0xd3, 0xc0, 0xb5, 0xdf, 0x71, 0x57, 0x5e, 0x26, 0xfe, 0x5b, 0x60, 0x52, 0xcf, 0x0b, 0x1d,
	0x7b, 0x8e, 0x53, 0x45, 0xce, 0x27, 0xf0, 0xc4, 0xa7, 0xef, 0x6d, 0x27, 0x0c, 0x04, 0x73, 0xa6,
	0x92, 0x5f, 0x33, 0x1b, 0xcf, 0x9c, 0x50, 0xe7, 0x8a, 0x49, 0x5b, 0x4c, 0x7d, 0x8c, 0xce, 0x20,
	0x2d, 0xb0, 0x94, 0xe0, 0x34, 0x08, 0x23, 0x97, 0x45, 0xcc, 0x9d, 0x97, 0x80, 0xd4, 0x97, 0x48,
	0x4a, 0xdb, 0x63, 0xd7, 0xcc, 0xb3, 0xea, 0x48, 0xda, 0x86, 0xf5, 0x59, 0x04, 0x09, 0xa3, 0x91,
	0x3a, 0x24, 0x24, 0x1d, 0x73, 0x95, 0x1b, 0xfb, 0x9c, 0x3a, 0x32, 0x8c, 0x2c, 0xa3, 0xa5, 0x77,
	0x36, 0x88, 0x01, 0x25, 0x19, 0xb1, 0xc0, 0xb5, 0x9a, 0x28, 0x78, 0x0f, 0xea, 0x2c, 0xa0, 0x63,
	0x8f, 0xd9, 0xe7, 0x1e, 0xbd, 0xb0, 0xd6, 0x51, 0x26, 0x57, 0x0e, 0x73, 0xa9, 0x1c, 0x1b, 0x58,
	0x8e, 0x5f, 0x42, 0x03, 0xab, 0x31, 0xe2, 0xce, 0x90, 0x0b, 0x49, 0x3e, 0x85, 0x42, 0xc0, 0x1d,
	0x4b, 0x6b, 0x15, 0x3a, 0xf5, 0xee, 0x77, 0x76, 0x13, 0x5c, 0xce, 0x8b, 0xec, 0x8e, 0xb8, 0xa3,
	0x40, 0xb8, 0xf3, 0x14, 0x2a, 0xc9, 0x5f, 0x02, 0xa0, 0xcf, 0x2a, 0xa5, 0xfe, 0x4f, 0x10, 0x7a,
	0xb5, 0xf6, 0x9f, 0x35, 0x30, 0x50, 0xf7, 0xb5, 0x60, 0x11, 0x4a, 0xae, 0x43, 0x65, 0x2a, 0x58,
	0x94, 0x16, 0xb6, 0xa8, 0xbc, 0x44, 0x02, 0xe2, 0x48, 0x4f, 0xa3, 0x71, 0xd9, 0x35, 0x77, 0xd8,
	0x3c, 0x5a, 0x01, 0xf4, 0x50, 0x24, 0x28, 0x55, 0x79, 0x09, 0xcf, 0xe5, 0x3b, 0x1a, 0x31, 0xfb,
	0x9a, 0x45, 0x42, 0x95, 0xb5, 0x94, 0xa2, 0x32, 0x8b, 0xb9, 0xbc, 0x14, 0x73, 0x05, 0x63, 0xfe,
	0xbd, 0x06, 0x9b, 0xe8, 0x55, 0x3f, 0x70, 0x8f, 0x43, 0x1e, 0xc8, 0x9e, 0xeb, 0x46, 0x4c, 0x08,
	0xf2, 0x15, 0x54, 0x52, 0x73, 0xca, 0xb9, 0x66, 0xf7, 0x59, 0x2e, 0x01, 0x0b, 0xe2, 0xbb, 0x83,
	0xe3, 0xb3, 0x58, 0xfa, 0x85, 0x7e, 0xf6, 0x7c, 0x3e, 0x6e, 0xd2, 0x80, 0xe2, 0x24, 0x8c, 0x12,
	0x84, 0xb6, 0x1f, 0x42, 0x6d, 0x26, 0x4a, 0xca, 0xa0, 0x9f, 0x3d, 0x37, 0xd7, 0xf0, 0xf7, 0x4b,
	0x53, 0x6b, 0xff, 0xb6, 0x08, 0x4d, 0xb4, 0xfe, 0x8a, 0x79, 0xf4, 0x06, 0x73, 0x64, 0x40, 0x89,
	0x07, 0x2e, 0x7b, 0x8f, 0x4e, 0x20, 0x54, 0x23, 0xc5, 0xb3, 0x03, 0xea, 0xb3, 0xe4, 0x80, 0x26,
	0x94, 0xb9, 0xeb, 0xa8, 0x2c, 0x16, 0x52, 0xc4, 0xbb, 0xa1, 0x4f, 0x79, 0x90, 0x64, 0x68, 0x13,
	0x1a, 0xf1, 0xb7, 0x1d, 0x5b, 0x8a, 0xfb, 0x40, 0x35, 0x91, 0x98, 0x64, 0x0d, 0xcc, 0xc5, 0x24,
	0xe1, 0xc7, 0x0d, 0xf0, 0x05, 0x18, 0x3e, 0x73, 0x39, 0xc5, 0x3e, 0x67, 0x42, 0x20, 0xfa, 0x17,
	0x61, 0xb0, 0x98, 0xb4, 0x3d, 0x78, 0xe4, 0x4f, 0x3d, 0xc9, 0x1d, 0x2a, 0xa4, 0x2d, 0x98, 0xc7,
	0x1c, 0x69, 0x4f, 0xa8, 0xbc, 0x9c, 0x19, 0xa9, 0xdd, 0xc1, 0xc8, 0x17, 0x60, 0xf0, 0x09, 0x8b,
	0xce, 0x67, 0x4a, 0x70, 0x07, 0xa5, 0x16, 0x58, 0xaa, 0x65, 0x5c, 0x3b, 0x9c, 0xca, 0x71, 0x38,
	0x0d, 0x5c, 0x6c, 0xdc, 0xb8, 0x6f, 0xe3, 0xce, 0x7a, 0x02, 0xdb, 0xb1, 0x04, 0x0f, 0x16, 0x05,
	0xe2, 0x0e, 0x7b, 0x04, 0x5b, 0xb1, 0x40, 0xd2, 0xde, 0x41, 0x3c, 0x24, 0x04, 0xb6, 0x99, 0x41,
	0x76, 0x80, 0x64, 0x6c, 0xc1, 0x84, 0x40, 0x5e, 0x73, 0x56, 0x16, 0xe4, 0x39, 0xa1, 0x90, 0xd8,
	0x72, 0x46, 0x3c, 0x3e, 0x65, 0x6c, 0xc3, 0x0e, 0xa6, 0x3e, 0xb6, 0xdd, 0xc2, 0x60, 0xdc, 0x58,
	0x42, 0x25, 0x41, 0x54, 0xfe, 0x5d, 0x83, 0xfb, 0x18, 0xe6, 0x61, 0x9a, 0xcd, 0xd9, 0xb8, 0x5f,
	0x87, 0x4a, 0x10, 0xba, 0x2c, 0x6d, 0x1a, 0x83, 0xbc, 0x80, 0x1a, 0x12, 0x66, 0x4d, 0xd3, 0xec,
	0x7e, 0x92, 0x4b, 0xd5, 0x92, 0x8d, 0xdd, 0x51, 0xe8, 0xb2, 0xd3, 0x9b, 0x09, 0xcb, 0x0f, 0xee,
	0x42, 0x3a, 0x67, 0x96, 0xc6, 0x6e, 0x8c, 0x23, 0x1c, 0x4d, 0x17, 0x39, 0x06, 0x42, 0xa9, 0xfd,
	0x04, 0xaa, 0x33, 0x8b, 0x55, 0x28, 0xbe, 0x3e, 0xe9, 0xbf, 0x32, 0xd7, 0x48, 0x0d, 0x4a, 0xaf,
	0xfa, 0xc3, 0xde, 0x1b, 0x53, 0x6b, 0xff, 0xa5, 0x00, 0x24, 0xef, 0x0a, 0x86, 0xb2, 0x09, 0x8d,
	0x0c, 0x2d, 0xf3, 0x43, 0x20, 0xf3, 0x29, 0x1e, 0x02, 0x73, 0x31, 0xcf, 0xe6, 0x7c, 0x16, 0x73,
	0x3c, 0xe7, 0x9f, 0xc2, 0x83, 0xcc, 0xd8, 0x64, 0x3a, 0xf6, 0xb8, 0xb8, 0x9c, 0x1b, 0x08, 0x6a,
	0x55, 0x7c, 0x17, 0x1e, 0xce, 0xa1, 0x73, 0x3a, 0x16, 0x4e, 0xc4, 0xc7, 0xd9, 0xd4, 0x28, 0xa3,
	0xd0, 0x0f, 0xa0, 0x32, 0xa1, 0x11, 0x0b, 0xa4, 0xb0, 0x2a, 0x38, 0xf8, 0x1e, 0x7f, 0x38, 0x99,
	0xe4, 0x73, 0xa8, 0x3a, 0x97, 0xdc, 0x73, 0x23, 0x16, 0x58, 0xd5, 0x3b, 0x69, 0xfc, 0x0c, 0x9a,
	0xe1, 0x84, 0x45, 0x14, 0x91, 0x81, 0x21, 0xd4, 0xb0, 0x6c, 0x9d, 0xdb, 0xf5, 0xb0, 0x64, 0x47,
	0xa9, 0x42, 0x5a, 0xb7, 0x0c, 0x44, 0xb0, 0x04, 0xa2, 0x3a, 0x82, 0xe8, 0x7b, 0x60, 0xe4, 0xb5,
	0x2a, 0x50, 0xe8, 0xed, 0xef, 0x9b, 0x6b, 0x04, 0xa0, 0xfc, 0xaa, 0x7f, 0x78, 0x74, 0xd6, 0x37,
	0xb5, 0xf6, 0x9f, 0x74, 0xd8, 0xce, 0x9f, 0xd7, 0xbf, 0x66, 0xc1, 0x47, 0x0a, 0xc4, 0x94, 0x88,
	0x7d, 0xc5, 0x6e, 0x92, 0x11, 0x44, 0x00, 0x62, 0xd2, 0x0c, 0x48, 0xa5, 0x8c, 0xc6, 0x83, 0xf3,
	0x30, 0x81, 0xd0, 0x5c, 0x21, 0x4b, 0xcb, 0xe0, 0x2d, 0xff, 0x77, 0xe0, 0xbd, 0x0d, 0xa9, 0x95,
	0x55, 0x48, 0xad, 0x2e, 0x37, 0x5f, 0x6d, 0x29, 0x6f, 0x98, 0xc9, 0xf6, 0xef, 0x4a, 0x09, 0x5a,
	0x4f, 0x24, 0x95, 0x03, 0xc9, 0xfc, 0x33, 0xea, 0x4d, 0x99, 0x5a, 0x08, 0xe1, 0xf8, 0x2d, 0x06,
	0xad, 0xe1, 0x40, 0xfa, 0x2c, 0xe7, 0x68, 0x4e, 0x38, 0x23, 0x1d, 0x8d, 0xdf, 0xbe, 0x64, 0x37,
	0xe4, 0x6b, 0xa8, 0xbb, 0x54, 0x52, 0xfb, 0x5a, 0x71, 0x85, 0xa5, 0x23, 0x4e, 0x3e, 0xfd, 0x98,
	0x81, 0x7d, 0x2a, 0x69, 0x7c, 0xf8, 0x16, 0x18, 0x42, 0x52, 0x95, 0x4b, 0xc9, 0xa2, 0x6b, 0xea,
	0x25, 0x7d, 0xf0, 0x00, 0x36, 0xc4, 0x74, 0x6c, 0xe7, 0x59, 0xc5, 0x2c, 0x54, 0x9f, 0x09, 0x49,
	0xfd, 0x09, 0x26, 0xbb, 0xb8, 0xf3, 0x37, 0x2d, 0x59, 0x2f, 0x99, 0xdd, 0x85, 0xf5, 0x52, 0x87,
	0x82, 0xba, 0x9d, 0xc4, 0x5d, 0xd7, 0x80, 0xa2, 0xe0, 0xbf, 0x4e, 0xe7, 0xc2, 0xb7, 0x60, 0x8c,
	0xb9, 0xf4, 0xe9, 0x24, 0x8d, 0xa1, 0x88, 0x31, 0xbc, 0xb8, 0x73, 0x0c, 0xf1, 0xe7, 0xcf, 0xd1,
	0x06, 0x12, 0x76, 0xba, 0x60, 0x2e, 0xd2, 0x16, 0x1d, 0x5a, 0x87, 0xca, 0x98, 0x4b, 0xdb, 0xa7,
	0xf1, 0x36, 0x2d, 0xee, 0xfc, 0x5b, 0x83, 0xf5, 0xc5, 0xe4, 0xf6, 0xa1, 0x28, 0x98, 0x77, 0x9e,
	0x94, 0xe5, 0xc7, 0x77, 0x2f, 0x4b, 0xee, 0x9b, 0xbc, 0x04, 0xa0, 0x42, 0x84, 0x0e, 0xa7, 0x72,
	0x56, 0xa2, 0xff, 0xd9, 0xd8, 0x06, 0xd4, 0xb0, 0x2a, 0xd9, 0x64, 0xdd, 0xf9, 0x3c, 0xb9, 0x5e,
	0xa5, 0x22, 0x4d, 0x28, 0x2b, 0x40, 0xcd, 0x2e, 0x4b, 0x26, 0x54, 0xd5, 0x77, 0x36, 0xf7, 0xda,
	0x7f, 0xd4, 0xe1, 0xd1, 0xd2, 0xfd, 0x78, 0xef, 0x92, 0x06, 0x17, 0x6c, 0x14, 0x4a, 0x7e, 0xfe,
	0xa1, 0x4b, 0xf2, 0x2f, 0xa0, 0x16, 0x7a, 0x2e, 0x42, 0x23, 0x5d, 0x0b, 0xf9, 0x60, 0x56, 0xd9,
	0xdc, 0x9d, 0x67, 0x28, 0x5f, 0x99, 0xb2, 0x15, 0xb0, 0x77, 0x89, 0xad, 0xc2, 0xff, 0x65, 0xab,
	0xfd, 0x15, 0x6c, 0x2c, 0x1f, 0x00, 0x50, 0x3e, 0x1a, 0x0d, 0x07, 0xa3, 0xbe, 0xb9, 0x46, 0x0c,
	0xa8, 0x1d, 0x0c, 0x7b, 0x27, 0xdf, 0xd8, 0x47, 0x07, 0x07, 0xa6, 0x46, 0xea, 0x50, 0x39, 0x3a,
	0x38, 0x40, 0x9e, 0xde, 0x3e, 0x84, 0xc7, 0x4b, 0xe7, 0xed, 0x33, 0x21, 0xa3, 0xf0, 0xe6, 0xa3,
	0x09, 0x59, 0x7e, 0x0d, 0xb5, 0xff, 0xa1, 0x27, 0x6b, 0x76, 0xde, 0x1e, 0x8e, 0x3f, 0x2c, 0xc6,
	0xbb, 0x20, 0xbb, 0x9c, 0xe2, 0x8e, 0x8f, 0x29, 0x73, 0x8b, 0x69, 0x79, 0xee, 0x19, 0xe4, 0x87,
	0xea, 0x35, 0x21, 0xb8, 0x93, 0xce, 0x3d, 0xad, 0x53, 0xef, 0x3e, 0x5a, 0x99, 0x2d, 0x9c, 0xb3,
	0x3f, 0x01, 0xc3, 0xc1, 0xac, 0xd9, 0x01, 0x46, 0x81, 0xfb, 0xaa, 0xde, 0xfd, 0xfe, 0x9d, 0x72,
	0x4c, 0xbe, 0x86, 0xa6, 0x1b, 0xe7, 0x20, 0x55, 0x2f, 0xa3, 0xfa, 0xb3, 0x95, 0xea, 0xf9, 0x94,
	0x7d, 0x09, 0x0d, 0xcc, 0xd4, 0xaf, 0xe2, 0x87, 0x97, 0x55, 0x41, 0xed, 0xd6, 0x4a, 0xed, 0xf4,
	0x81, 0x96, 0x9b, 0x30, 0xf8, 0xc4, 0x6b, 0xff, 0x46, 0x83, 0x07, 0x4b, 0xf2, 0xaa, 0xc4, 0x6a,
	0x0a, 0xdc, 0x31, 0xa7, 0xbb, 0x00, 0x5c, 0x32, 0x3f, 0x1e, 0x33, 0x98, 0xd3, 0x7a, 0x77, 0x67,
	0x75, 0x1b, 0xe6, 0xdd, 0x28, 0xa2, 0x1b, 0xff, 0xd2, 0x93, 0x56, 0x3b, 0x64, 0x42, 0xd0, 0x0b,
	0x46, 0x3a, 0xc9, 0xc3, 0x02, 0x4b, 0xa2, 0x61, 0x7c, 0x5b, 0x39, 0x93, 0xb3, 0x37, 0xc9, 0x67,
	0xe9, 0x05, 0x1b, 0x45, 0x75, 0x14, 0xbd, 0x9f, 0x13, 0xcd, 0xee, 0xe6, 0x5d, 0x68, 0xce, 0xad,
	0x47, 0x25, 0x5f, 0x40, 0xf9, 0x9d, 0xd5, 0x7b, 0x9c, 0xfc, 0x14, 0x36, 0x33, 0x9d, 0xdc, 0x7e,
	0x54, 0x9a, 0x4f, 0x6e, 0xd7, 0xcc, 0x36, 0xf2, 0x33, 0xa8, 0x06, 0xdc, 0xb1, 0x3d, 0x2e, 0x64,
	0x02, 0x92, 0xcd, 0xdb, 0xde, 0x65, 0xa4, 0x0b, 0x80, 0x35, 0xc5, 0x13, 0x12, 0x3c, 0x3c, 0x5e,
	0x59, 0xd1, 0x18, 0xf2, 0xcf, 0x93, 0x91, 0xa5, 0x16, 0x55, 0x02, 0x82, 0xa7, 0x2b, 0x55, 0xd2,
	0xa2, 0xaa, 0x19, 0x75, 0x2f, 0xf6, 0x36, 0x0c, 0xb8, 0x0c, 0xa3, 0x34, 0xe5, 0x3f, 0x82, 0x22,
	0x16, 0x55, 0xbb, 0x6d, 0xa9, 0xe7, 0x44, 0x77, 0x93, 0x5f, 0x5c, 0xea, 0x04, 0xc0, 0x09, 0x7d,
	0x5f, 0x3d, 0xba, 0xb9, 0x9b, 0xdc, 0x2e, 0xea, 0x50, 0xf0, 0xc5, 0x85, 0x55, 0x68, 0x15, 0x3a,
	0x8d, 0xf6, 0x5f, 0x35, 0xa8, 0xcf, 0x2b, 0x18, 0x50, 0x53, 0x17, 0x4e, 0x7b, 0x30, 0x3a, 0x38,
	0x32, 0xd7, 0x48, 0x13, 0x00, 0x6f, 0x9d, 0xf1, 0xb7, 0x46, 0x08, 0x34, 0x0f, 0x5f, 0x0f, 0x4f,
	0x07, 0x7b, 0xbd, 0x93, 0xd3, 0x98, 0xa6, 0x13, 0x0b, 0x36, 0x33, 0x5a, 0xff, 0xac, 0x3f, 0x4a,
	0x38, 0x05, 0xd2, 0x80, 0xea, 0x68, 0xb0, 0x67, 0x0f, 0x07, 0x27, 0xa7, 0x66, 0x91, 0x6c, 0xc3,
	0xbd, 0xe3, 0x6f, 0xde, 0x9c, 0x0c, 0xf6, 0x7a, 0x43, 0x7b, 0x38, 0x18, 0xbd, 0x8c, 0x65, 0xcd,
	0x12, 0x79, 0x08, 0xdb, 0x79, 0xc6, 0xc9, 0x69, 0xef, 0xd4, 0xde, 0xef, 0x9d, 0xf6, 0xcc, 0xf2,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x66, 0x3c, 0x91, 0x64, 0xc0, 0x11, 0x00, 0x00,
}
