// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redsdn.proto

/*
Package redsdn is a generated protocol buffer package.

golang配置

It is generated from these files:
	redsdn.proto

It has these top-level messages:
	ProtoPhysicalLinkInfo
	ProtoPhysicalLinkQuality
	ProtoNicList
	ProtoUserInfo
	ProtoEndPointAddress
	ProtoRelayInfo
	ProtoMulticastLinkInfo
	ProtoMulticastInfo
	ProtoMulticastEventInfo
	ProtoStatItemValue
	ProtoPhysicalLinkChangeNotify
	ProtoPhysicalLinkDestroyNotify
	ProtoPhysicalLinkEvent
	ProtoPhysicalLinkStatData
	ProtoMessage
	ProtoMonitorMessage
*/
package redsdn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IP 协议版本枚举
type ProtoEndPointAddress_IPVersion int32

const (
	ProtoEndPointAddress_V4 ProtoEndPointAddress_IPVersion = 0
	ProtoEndPointAddress_V6 ProtoEndPointAddress_IPVersion = 1
)

var ProtoEndPointAddress_IPVersion_name = map[int32]string{
	0: "V4",
	1: "V6",
}
var ProtoEndPointAddress_IPVersion_value = map[string]int32{
	"V4": 0,
	"V6": 1,
}

func (x ProtoEndPointAddress_IPVersion) Enum() *ProtoEndPointAddress_IPVersion {
	p := new(ProtoEndPointAddress_IPVersion)
	*p = x
	return p
}
func (x ProtoEndPointAddress_IPVersion) String() string {
	return proto.EnumName(ProtoEndPointAddress_IPVersion_name, int32(x))
}
func (x *ProtoEndPointAddress_IPVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoEndPointAddress_IPVersion_value, data, "ProtoEndPointAddress_IPVersion")
	if err != nil {
		return err
	}
	*x = ProtoEndPointAddress_IPVersion(value)
	return nil
}
func (ProtoEndPointAddress_IPVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type ProtoMulticastLinkInfo_NodeType int32

const (
	ProtoMulticastLinkInfo_USER  ProtoMulticastLinkInfo_NodeType = 0
	ProtoMulticastLinkInfo_RELAY ProtoMulticastLinkInfo_NodeType = 1
)

var ProtoMulticastLinkInfo_NodeType_name = map[int32]string{
	0: "USER",
	1: "RELAY",
}
var ProtoMulticastLinkInfo_NodeType_value = map[string]int32{
	"USER":  0,
	"RELAY": 1,
}

func (x ProtoMulticastLinkInfo_NodeType) Enum() *ProtoMulticastLinkInfo_NodeType {
	p := new(ProtoMulticastLinkInfo_NodeType)
	*p = x
	return p
}
func (x ProtoMulticastLinkInfo_NodeType) String() string {
	return proto.EnumName(ProtoMulticastLinkInfo_NodeType_name, int32(x))
}
func (x *ProtoMulticastLinkInfo_NodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMulticastLinkInfo_NodeType_value, data, "ProtoMulticastLinkInfo_NodeType")
	if err != nil {
		return err
	}
	*x = ProtoMulticastLinkInfo_NodeType(value)
	return nil
}
func (ProtoMulticastLinkInfo_NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type ProtoMulticastInfo_OperationType int32

const (
	ProtoMulticastInfo_ADD    ProtoMulticastInfo_OperationType = 0
	ProtoMulticastInfo_REMOVE ProtoMulticastInfo_OperationType = 1
)

var ProtoMulticastInfo_OperationType_name = map[int32]string{
	0: "ADD",
	1: "REMOVE",
}
var ProtoMulticastInfo_OperationType_value = map[string]int32{
	"ADD":    0,
	"REMOVE": 1,
}

func (x ProtoMulticastInfo_OperationType) Enum() *ProtoMulticastInfo_OperationType {
	p := new(ProtoMulticastInfo_OperationType)
	*p = x
	return p
}
func (x ProtoMulticastInfo_OperationType) String() string {
	return proto.EnumName(ProtoMulticastInfo_OperationType_name, int32(x))
}
func (x *ProtoMulticastInfo_OperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMulticastInfo_OperationType_value, data, "ProtoMulticastInfo_OperationType")
	if err != nil {
		return err
	}
	*x = ProtoMulticastInfo_OperationType(value)
	return nil
}
func (ProtoMulticastInfo_OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type ProtoPhysicalLinkChangeNotify_PhysicalLinkState int32

const (
	ProtoPhysicalLinkChangeNotify_ONLINE    ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 0
	ProtoPhysicalLinkChangeNotify_FLASH_OFF ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 1
	ProtoPhysicalLinkChangeNotify_OFFLINE   ProtoPhysicalLinkChangeNotify_PhysicalLinkState = 2
)

var ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name = map[int32]string{
	0: "ONLINE",
	1: "FLASH_OFF",
	2: "OFFLINE",
}
var ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value = map[string]int32{
	"ONLINE":    0,
	"FLASH_OFF": 1,
	"OFFLINE":   2,
}

func (x ProtoPhysicalLinkChangeNotify_PhysicalLinkState) Enum() *ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	p := new(ProtoPhysicalLinkChangeNotify_PhysicalLinkState)
	*p = x
	return p
}
func (x ProtoPhysicalLinkChangeNotify_PhysicalLinkState) String() string {
	return proto.EnumName(ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name, int32(x))
}
func (x *ProtoPhysicalLinkChangeNotify_PhysicalLinkState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value, data, "ProtoPhysicalLinkChangeNotify_PhysicalLinkState")
	if err != nil {
		return err
	}
	*x = ProtoPhysicalLinkChangeNotify_PhysicalLinkState(value)
	return nil
}
func (ProtoPhysicalLinkChangeNotify_PhysicalLinkState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

// 消息类型枚举
type ProtoMonitorMessage_MessageType int32

const (
	ProtoMonitorMessage_USER_INFO               ProtoMonitorMessage_MessageType = 0
	ProtoMonitorMessage_RELAY_INFO              ProtoMonitorMessage_MessageType = 1
	ProtoMonitorMessage_MULTICAST_INFO          ProtoMonitorMessage_MessageType = 2
	ProtoMonitorMessage_MULTICAST_EVENT_INFO    ProtoMonitorMessage_MessageType = 3
	ProtoMonitorMessage_NIC_LIST                ProtoMonitorMessage_MessageType = 4
	ProtoMonitorMessage_PHYSICAL_LINK_EVENT     ProtoMonitorMessage_MessageType = 5
	ProtoMonitorMessage_PHYSICAL_LINK_STAT_DATA ProtoMonitorMessage_MessageType = 6
)

var ProtoMonitorMessage_MessageType_name = map[int32]string{
	0: "USER_INFO",
	1: "RELAY_INFO",
	2: "MULTICAST_INFO",
	3: "MULTICAST_EVENT_INFO",
	4: "NIC_LIST",
	5: "PHYSICAL_LINK_EVENT",
	6: "PHYSICAL_LINK_STAT_DATA",
}
var ProtoMonitorMessage_MessageType_value = map[string]int32{
	"USER_INFO":               0,
	"RELAY_INFO":              1,
	"MULTICAST_INFO":          2,
	"MULTICAST_EVENT_INFO":    3,
	"NIC_LIST":                4,
	"PHYSICAL_LINK_EVENT":     5,
	"PHYSICAL_LINK_STAT_DATA": 6,
}

func (x ProtoMonitorMessage_MessageType) Enum() *ProtoMonitorMessage_MessageType {
	p := new(ProtoMonitorMessage_MessageType)
	*p = x
	return p
}
func (x ProtoMonitorMessage_MessageType) String() string {
	return proto.EnumName(ProtoMonitorMessage_MessageType_name, int32(x))
}
func (x *ProtoMonitorMessage_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoMonitorMessage_MessageType_value, data, "ProtoMonitorMessage_MessageType")
	if err != nil {
		return err
	}
	*x = ProtoMonitorMessage_MessageType(value)
	return nil
}
func (ProtoMonitorMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

// =============================================================================================================================
// 物理链路基础信息
// @since 1.0
type ProtoPhysicalLinkInfo struct {
	PhysicalLinkId   *string `protobuf:"bytes,1,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	Direction        *uint32 `protobuf:"varint,2,req,name=direction" json:"direction,omitempty"`
	LocalNetType     *uint32 `protobuf:"varint,3,req,name=local_net_type,json=localNetType" json:"local_net_type,omitempty"`
	LocalAddr        *string `protobuf:"bytes,4,req,name=local_addr,json=localAddr" json:"local_addr,omitempty"`
	DestNetType      *uint32 `protobuf:"varint,5,req,name=dest_net_type,json=destNetType" json:"dest_net_type,omitempty"`
	DestAddr         *string `protobuf:"bytes,6,req,name=dest_addr,json=destAddr" json:"dest_addr,omitempty"`
	RoleType         *uint32 `protobuf:"varint,7,req,name=role_type,json=roleType" json:"role_type,omitempty"`
	TickTime         *uint64 `protobuf:"varint,8,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime          *uint64 `protobuf:"varint,9,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoPhysicalLinkInfo) Reset()                    { *m = ProtoPhysicalLinkInfo{} }
func (m *ProtoPhysicalLinkInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkInfo) ProtoMessage()               {}
func (*ProtoPhysicalLinkInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoPhysicalLinkInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetLocalNetType() uint32 {
	if m != nil && m.LocalNetType != nil {
		return *m.LocalNetType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetLocalAddr() string {
	if m != nil && m.LocalAddr != nil {
		return *m.LocalAddr
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetDestNetType() uint32 {
	if m != nil && m.DestNetType != nil {
		return *m.DestNetType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetDestAddr() string {
	if m != nil && m.DestAddr != nil {
		return *m.DestAddr
	}
	return ""
}

func (m *ProtoPhysicalLinkInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoPhysicalLinkInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// 物理链路质量
// @since 1.0
type ProtoPhysicalLinkQuality struct {
	PhysicalLinkId              *string `protobuf:"bytes,1,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	Idx                         *uint32 `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	Rtt                         *uint32 `protobuf:"varint,3,req,name=rtt" json:"rtt,omitempty"`
	LossRate                    *uint32 `protobuf:"varint,4,req,name=loss_rate,json=lossRate" json:"loss_rate,omitempty"`
	Jitter                      *uint32 `protobuf:"varint,5,req,name=jitter" json:"jitter,omitempty"`
	Direction                   *uint32 `protobuf:"varint,6,req,name=direction" json:"direction,omitempty"`
	BandWidth                   *uint32 `protobuf:"varint,7,req,name=band_width,json=bandWidth" json:"band_width,omitempty"`
	AllocBandWidth              *uint32 `protobuf:"varint,8,req,name=alloc_band_width,json=allocBandWidth" json:"alloc_band_width,omitempty"`
	MaxConsecutiveLossPacketSum *uint32 `protobuf:"varint,9,req,name=max_consecutive_loss_packet_sum,json=maxConsecutiveLossPacketSum" json:"max_consecutive_loss_packet_sum,omitempty"`
	MaxUnorderedPacketSum       *uint32 `protobuf:"varint,10,req,name=max_unordered_packet_sum,json=maxUnorderedPacketSum" json:"max_unordered_packet_sum,omitempty"`
	RttLevel                    *uint32 `protobuf:"varint,11,req,name=rtt_level,json=rttLevel" json:"rtt_level,omitempty"`
	LossRateLevel               *uint32 `protobuf:"varint,12,req,name=loss_rate_level,json=lossRateLevel" json:"loss_rate_level,omitempty"`
	StabilityFactor             *int32  `protobuf:"zigzag32,13,req,name=stability_factor,json=stabilityFactor" json:"stability_factor,omitempty"`
	Trend                       *uint32 `protobuf:"varint,14,req,name=trend" json:"trend,omitempty"`
	EnableFlag                  *int32  `protobuf:"zigzag32,15,req,name=enable_flag,json=enableFlag" json:"enable_flag,omitempty"`
	TickTime                    *uint64 `protobuf:"varint,16,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime                     *uint64 `protobuf:"varint,17,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized            []byte  `json:"-"`
}

func (m *ProtoPhysicalLinkQuality) Reset()                    { *m = ProtoPhysicalLinkQuality{} }
func (m *ProtoPhysicalLinkQuality) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkQuality) ProtoMessage()               {}
func (*ProtoPhysicalLinkQuality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoPhysicalLinkQuality) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkQuality) GetIdx() uint32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetRtt() uint32 {
	if m != nil && m.Rtt != nil {
		return *m.Rtt
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetLossRate() uint32 {
	if m != nil && m.LossRate != nil {
		return *m.LossRate
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetJitter() uint32 {
	if m != nil && m.Jitter != nil {
		return *m.Jitter
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetBandWidth() uint32 {
	if m != nil && m.BandWidth != nil {
		return *m.BandWidth
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetAllocBandWidth() uint32 {
	if m != nil && m.AllocBandWidth != nil {
		return *m.AllocBandWidth
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetMaxConsecutiveLossPacketSum() uint32 {
	if m != nil && m.MaxConsecutiveLossPacketSum != nil {
		return *m.MaxConsecutiveLossPacketSum
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetMaxUnorderedPacketSum() uint32 {
	if m != nil && m.MaxUnorderedPacketSum != nil {
		return *m.MaxUnorderedPacketSum
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetRttLevel() uint32 {
	if m != nil && m.RttLevel != nil {
		return *m.RttLevel
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetLossRateLevel() uint32 {
	if m != nil && m.LossRateLevel != nil {
		return *m.LossRateLevel
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetStabilityFactor() int32 {
	if m != nil && m.StabilityFactor != nil {
		return *m.StabilityFactor
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetTrend() uint32 {
	if m != nil && m.Trend != nil {
		return *m.Trend
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetEnableFlag() int32 {
	if m != nil && m.EnableFlag != nil {
		return *m.EnableFlag
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoPhysicalLinkQuality) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// IP 列表
// @since 1.0
type ProtoNicList struct {
	Nic              []*ProtoNicList_NicInfo `protobuf:"bytes,1,rep,name=nic" json:"nic,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ProtoNicList) Reset()                    { *m = ProtoNicList{} }
func (m *ProtoNicList) String() string            { return proto.CompactTextString(m) }
func (*ProtoNicList) ProtoMessage()               {}
func (*ProtoNicList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoNicList) GetNic() []*ProtoNicList_NicInfo {
	if m != nil {
		return m.Nic
	}
	return nil
}

type ProtoNicList_NicInfo struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoNicList_NicInfo) Reset()                    { *m = ProtoNicList_NicInfo{} }
func (m *ProtoNicList_NicInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoNicList_NicInfo) ProtoMessage()               {}
func (*ProtoNicList_NicInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ProtoNicList_NicInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ProtoNicList_NicInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

// =============================================================================================================================
// 用户基础信息汇报
// @since 1.0
type ProtoUserInfo struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	UserType         *uint32 `protobuf:"varint,2,req,name=user_type,json=userType" json:"user_type,omitempty"`
	DeviceType       *uint32 `protobuf:"varint,3,req,name=device_type,json=deviceType" json:"device_type,omitempty"`
	Os               *string `protobuf:"bytes,4,req,name=os" json:"os,omitempty"`
	SoftwareVersion  *string `protobuf:"bytes,5,req,name=software_version,json=softwareVersion" json:"software_version,omitempty"`
	TickTime         *uint64 `protobuf:"varint,6,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime          *uint64 `protobuf:"varint,7,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoUserInfo) Reset()                    { *m = ProtoUserInfo{} }
func (m *ProtoUserInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoUserInfo) ProtoMessage()               {}
func (*ProtoUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoUserInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ProtoUserInfo) GetUserType() uint32 {
	if m != nil && m.UserType != nil {
		return *m.UserType
	}
	return 0
}

func (m *ProtoUserInfo) GetDeviceType() uint32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *ProtoUserInfo) GetOs() string {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return ""
}

func (m *ProtoUserInfo) GetSoftwareVersion() string {
	if m != nil && m.SoftwareVersion != nil {
		return *m.SoftwareVersion
	}
	return ""
}

func (m *ProtoUserInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoUserInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// @since 1.0
type ProtoEndPointAddress struct {
	Version          *ProtoEndPointAddress_IPVersion `protobuf:"varint,1,req,name=version,enum=redsdn.ProtoEndPointAddress_IPVersion,def=0" json:"version,omitempty"`
	Ip               *string                         `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *uint32                         `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ProtoEndPointAddress) Reset()                    { *m = ProtoEndPointAddress{} }
func (m *ProtoEndPointAddress) String() string            { return proto.CompactTextString(m) }
func (*ProtoEndPointAddress) ProtoMessage()               {}
func (*ProtoEndPointAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_ProtoEndPointAddress_Version ProtoEndPointAddress_IPVersion = ProtoEndPointAddress_V4

func (m *ProtoEndPointAddress) GetVersion() ProtoEndPointAddress_IPVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_ProtoEndPointAddress_Version
}

func (m *ProtoEndPointAddress) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *ProtoEndPointAddress) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

// Relay 信息汇报
// @since 1.0
type ProtoRelayInfo struct {
	Index                      *uint32               `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	RelayName                  *string               `protobuf:"bytes,2,req,name=relay_name,json=relayName" json:"relay_name,omitempty"`
	IdcId                      *uint32               `protobuf:"varint,3,req,name=idc_id,json=idcId" json:"idc_id,omitempty"`
	Domain                     *string               `protobuf:"bytes,4,req,name=domain" json:"domain,omitempty"`
	DomainIndex                *uint32               `protobuf:"varint,5,req,name=domain_index,json=domainIndex" json:"domain_index,omitempty"`
	Isp                        *string               `protobuf:"bytes,6,req,name=isp" json:"isp,omitempty"`
	IspIndex                   *uint32               `protobuf:"varint,7,req,name=isp_index,json=ispIndex" json:"isp_index,omitempty"`
	MediaAddress               *ProtoEndPointAddress `protobuf:"bytes,8,req,name=media_address,json=mediaAddress" json:"media_address,omitempty"`
	MulticastSelectPathAddress *ProtoEndPointAddress `protobuf:"bytes,9,req,name=multicast_select_path_address,json=multicastSelectPathAddress" json:"multicast_select_path_address,omitempty"`
	IperfAddress               *ProtoEndPointAddress `protobuf:"bytes,10,req,name=iperf_address,json=iperfAddress" json:"iperf_address,omitempty"`
	RatedOutboundBandwidth     *uint32               `protobuf:"varint,11,req,name=rated_outbound_bandwidth,json=ratedOutboundBandwidth" json:"rated_outbound_bandwidth,omitempty"`
	RatedInboundBandwidth      *uint32               `protobuf:"varint,12,req,name=rated_inbound_bandwidth,json=ratedInboundBandwidth" json:"rated_inbound_bandwidth,omitempty"`
	RatedMaxConnections        *uint32               `protobuf:"varint,13,req,name=rated_max_connections,json=ratedMaxConnections" json:"rated_max_connections,omitempty"`
	RatedMaxSessions           *uint32               `protobuf:"varint,14,req,name=rated_max_sessions,json=ratedMaxSessions" json:"rated_max_sessions,omitempty"`
	RatedCost                  *uint32               `protobuf:"varint,15,req,name=rated_cost,json=ratedCost" json:"rated_cost,omitempty"`
	DetectionNum               *uint32               `protobuf:"varint,16,req,name=detection_num,json=detectionNum" json:"detection_num,omitempty"`
	TickTime                   *uint64               `protobuf:"varint,17,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime                    *uint64               `protobuf:"varint,18,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized           []byte                `json:"-"`
}

func (m *ProtoRelayInfo) Reset()                    { *m = ProtoRelayInfo{} }
func (m *ProtoRelayInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoRelayInfo) ProtoMessage()               {}
func (*ProtoRelayInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProtoRelayInfo) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoRelayInfo) GetRelayName() string {
	if m != nil && m.RelayName != nil {
		return *m.RelayName
	}
	return ""
}

func (m *ProtoRelayInfo) GetIdcId() uint32 {
	if m != nil && m.IdcId != nil {
		return *m.IdcId
	}
	return 0
}

func (m *ProtoRelayInfo) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *ProtoRelayInfo) GetDomainIndex() uint32 {
	if m != nil && m.DomainIndex != nil {
		return *m.DomainIndex
	}
	return 0
}

func (m *ProtoRelayInfo) GetIsp() string {
	if m != nil && m.Isp != nil {
		return *m.Isp
	}
	return ""
}

func (m *ProtoRelayInfo) GetIspIndex() uint32 {
	if m != nil && m.IspIndex != nil {
		return *m.IspIndex
	}
	return 0
}

func (m *ProtoRelayInfo) GetMediaAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.MediaAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetMulticastSelectPathAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.MulticastSelectPathAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetIperfAddress() *ProtoEndPointAddress {
	if m != nil {
		return m.IperfAddress
	}
	return nil
}

func (m *ProtoRelayInfo) GetRatedOutboundBandwidth() uint32 {
	if m != nil && m.RatedOutboundBandwidth != nil {
		return *m.RatedOutboundBandwidth
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedInboundBandwidth() uint32 {
	if m != nil && m.RatedInboundBandwidth != nil {
		return *m.RatedInboundBandwidth
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedMaxConnections() uint32 {
	if m != nil && m.RatedMaxConnections != nil {
		return *m.RatedMaxConnections
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedMaxSessions() uint32 {
	if m != nil && m.RatedMaxSessions != nil {
		return *m.RatedMaxSessions
	}
	return 0
}

func (m *ProtoRelayInfo) GetRatedCost() uint32 {
	if m != nil && m.RatedCost != nil {
		return *m.RatedCost
	}
	return 0
}

func (m *ProtoRelayInfo) GetDetectionNum() uint32 {
	if m != nil && m.DetectionNum != nil {
		return *m.DetectionNum
	}
	return 0
}

func (m *ProtoRelayInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoRelayInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// @since 1.0
type ProtoMulticastLinkInfo struct {
	NodeId           *uint32                          `protobuf:"varint,1,req,name=node_id,json=nodeId" json:"node_id,omitempty"`
	NodeType         *ProtoMulticastLinkInfo_NodeType `protobuf:"varint,2,req,name=node_type,json=nodeType,enum=redsdn.ProtoMulticastLinkInfo_NodeType" json:"node_type,omitempty"`
	RoleType         *uint32                          `protobuf:"varint,3,req,name=role_type,json=roleType" json:"role_type,omitempty"`
	PhysicalLinkId   *string                          `protobuf:"bytes,4,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	LogicalLinkId    *uint32                          `protobuf:"varint,5,req,name=logical_link_id,json=logicalLinkId" json:"logical_link_id,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ProtoMulticastLinkInfo) Reset()                    { *m = ProtoMulticastLinkInfo{} }
func (m *ProtoMulticastLinkInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoMulticastLinkInfo) ProtoMessage()               {}
func (*ProtoMulticastLinkInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProtoMulticastLinkInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastLinkInfo) GetNodeType() ProtoMulticastLinkInfo_NodeType {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return ProtoMulticastLinkInfo_USER
}

func (m *ProtoMulticastLinkInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoMulticastLinkInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoMulticastLinkInfo) GetLogicalLinkId() uint32 {
	if m != nil && m.LogicalLinkId != nil {
		return *m.LogicalLinkId
	}
	return 0
}

// 组播信息汇报
// @since 1.0
type ProtoMulticastInfo struct {
	MulticastId               *uint64                           `protobuf:"varint,1,req,name=multicast_id,json=multicastId" json:"multicast_id,omitempty"`
	RoleType                  *uint32                           `protobuf:"varint,2,req,name=role_type,json=roleType" json:"role_type,omitempty"`
	NodeId                    *uint32                           `protobuf:"varint,3,req,name=node_id,json=nodeId" json:"node_id,omitempty"`
	NodeType                  *uint32                           `protobuf:"varint,4,req,name=node_type,json=nodeType" json:"node_type,omitempty"`
	MulticastPublishVersion   *uint32                           `protobuf:"varint,5,opt,name=multicast_publish_version,json=multicastPublishVersion" json:"multicast_publish_version,omitempty"`
	MulticastSubscribeVersion *uint32                           `protobuf:"varint,6,opt,name=multicast_subscribe_version,json=multicastSubscribeVersion" json:"multicast_subscribe_version,omitempty"`
	Parents                   []*ProtoMulticastLinkInfo         `protobuf:"bytes,7,rep,name=parents" json:"parents,omitempty"`
	Children                  []*ProtoMulticastLinkInfo         `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
	OperationType             *ProtoMulticastInfo_OperationType `protobuf:"varint,9,req,name=operation_type,json=operationType,enum=redsdn.ProtoMulticastInfo_OperationType" json:"operation_type,omitempty"`
	TickTime                  *uint64                           `protobuf:"varint,10,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime                   *uint64                           `protobuf:"varint,11,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized          []byte                            `json:"-"`
}

func (m *ProtoMulticastInfo) Reset()                    { *m = ProtoMulticastInfo{} }
func (m *ProtoMulticastInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoMulticastInfo) ProtoMessage()               {}
func (*ProtoMulticastInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProtoMulticastInfo) GetMulticastId() uint64 {
	if m != nil && m.MulticastId != nil {
		return *m.MulticastId
	}
	return 0
}

func (m *ProtoMulticastInfo) GetRoleType() uint32 {
	if m != nil && m.RoleType != nil {
		return *m.RoleType
	}
	return 0
}

func (m *ProtoMulticastInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastInfo) GetNodeType() uint32 {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return 0
}

func (m *ProtoMulticastInfo) GetMulticastPublishVersion() uint32 {
	if m != nil && m.MulticastPublishVersion != nil {
		return *m.MulticastPublishVersion
	}
	return 0
}

func (m *ProtoMulticastInfo) GetMulticastSubscribeVersion() uint32 {
	if m != nil && m.MulticastSubscribeVersion != nil {
		return *m.MulticastSubscribeVersion
	}
	return 0
}

func (m *ProtoMulticastInfo) GetParents() []*ProtoMulticastLinkInfo {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ProtoMulticastInfo) GetChildren() []*ProtoMulticastLinkInfo {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ProtoMulticastInfo) GetOperationType() ProtoMulticastInfo_OperationType {
	if m != nil && m.OperationType != nil {
		return *m.OperationType
	}
	return ProtoMulticastInfo_ADD
}

func (m *ProtoMulticastInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoMulticastInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// 组播事件汇报
// @since 1.0
type ProtoMulticastEventInfo struct {
	MulticastId      *uint64                          `protobuf:"varint,1,req,name=multicast_id,json=multicastId" json:"multicast_id,omitempty"`
	EventKey         *string                          `protobuf:"bytes,2,req,name=event_key,json=eventKey" json:"event_key,omitempty"`
	EventType        *int32                           `protobuf:"varint,3,req,name=event_type,json=eventType" json:"event_type,omitempty"`
	EventInfo        *string                          `protobuf:"bytes,4,req,name=event_info,json=eventInfo" json:"event_info,omitempty"`
	NodeId           *uint32                          `protobuf:"varint,5,req,name=node_id,json=nodeId" json:"node_id,omitempty"`
	NodeType         *ProtoMulticastLinkInfo_NodeType `protobuf:"varint,6,req,name=node_type,json=nodeType,enum=redsdn.ProtoMulticastLinkInfo_NodeType" json:"node_type,omitempty"`
	PhysicalLinkId   *string                          `protobuf:"bytes,7,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	LogicalLinkId    *uint32                          `protobuf:"varint,8,req,name=logical_link_id,json=logicalLinkId" json:"logical_link_id,omitempty"`
	TickTime         *uint64                          `protobuf:"varint,9,req,name=tick_time,json=tickTime" json:"tick_time,omitempty"`
	UtcTime          *uint64                          `protobuf:"varint,10,req,name=utc_time,json=utcTime" json:"utc_time,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ProtoMulticastEventInfo) Reset()                    { *m = ProtoMulticastEventInfo{} }
func (m *ProtoMulticastEventInfo) String() string            { return proto.CompactTextString(m) }
func (*ProtoMulticastEventInfo) ProtoMessage()               {}
func (*ProtoMulticastEventInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ProtoMulticastEventInfo) GetMulticastId() uint64 {
	if m != nil && m.MulticastId != nil {
		return *m.MulticastId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetEventKey() string {
	if m != nil && m.EventKey != nil {
		return *m.EventKey
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetEventInfo() string {
	if m != nil && m.EventInfo != nil {
		return *m.EventInfo
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetNodeId() uint32 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetNodeType() ProtoMulticastLinkInfo_NodeType {
	if m != nil && m.NodeType != nil {
		return *m.NodeType
	}
	return ProtoMulticastLinkInfo_USER
}

func (m *ProtoMulticastEventInfo) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoMulticastEventInfo) GetLogicalLinkId() uint32 {
	if m != nil && m.LogicalLinkId != nil {
		return *m.LogicalLinkId
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetTickTime() uint64 {
	if m != nil && m.TickTime != nil {
		return *m.TickTime
	}
	return 0
}

func (m *ProtoMulticastEventInfo) GetUtcTime() uint64 {
	if m != nil && m.UtcTime != nil {
		return *m.UtcTime
	}
	return 0
}

// =============================================================================================================================
// StatItemValue 统计数据定义
// @since 2.0
// @date 2018/2/1
type ProtoStatItemValue struct {
	ObjKey           *ProtoStatItemValue_ProtoStatObjKey  `protobuf:"bytes,1,req,name=obj_key,json=objKey" json:"obj_key,omitempty"`
	DataValues       []*ProtoStatItemValue_ProtoDataValue `protobuf:"bytes,2,rep,name=data_values,json=dataValues" json:"data_values,omitempty"`
	StatInterval     *uint32                              `protobuf:"varint,3,req,name=stat_interval,json=statInterval" json:"stat_interval,omitempty"`
	SubStatInterval  *uint32                              `protobuf:"varint,4,req,name=sub_stat_interval,json=subStatInterval" json:"sub_stat_interval,omitempty"`
	Timestamp        *uint64                              `protobuf:"varint,5,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *ProtoStatItemValue) Reset()                    { *m = ProtoStatItemValue{} }
func (m *ProtoStatItemValue) String() string            { return proto.CompactTextString(m) }
func (*ProtoStatItemValue) ProtoMessage()               {}
func (*ProtoStatItemValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ProtoStatItemValue) GetObjKey() *ProtoStatItemValue_ProtoStatObjKey {
	if m != nil {
		return m.ObjKey
	}
	return nil
}

func (m *ProtoStatItemValue) GetDataValues() []*ProtoStatItemValue_ProtoDataValue {
	if m != nil {
		return m.DataValues
	}
	return nil
}

func (m *ProtoStatItemValue) GetStatInterval() uint32 {
	if m != nil && m.StatInterval != nil {
		return *m.StatInterval
	}
	return 0
}

func (m *ProtoStatItemValue) GetSubStatInterval() uint32 {
	if m != nil && m.SubStatInterval != nil {
		return *m.SubStatInterval
	}
	return 0
}

func (m *ProtoStatItemValue) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ProtoStatItemValue_ProtoDataValue struct {
	Index            *uint32                                               `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	Sum              *uint32                                               `protobuf:"varint,2,req,name=sum" json:"sum,omitempty"`
	Size             *uint32                                               `protobuf:"varint,3,req,name=size" json:"size,omitempty"`
	BitmapValues     []*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue `protobuf:"bytes,4,rep,name=bitmap_values,json=bitmapValues" json:"bitmap_values,omitempty"`
	XXX_unrecognized []byte                                                `json:"-"`
}

func (m *ProtoStatItemValue_ProtoDataValue) Reset()         { *m = ProtoStatItemValue_ProtoDataValue{} }
func (m *ProtoStatItemValue_ProtoDataValue) String() string { return proto.CompactTextString(m) }
func (*ProtoStatItemValue_ProtoDataValue) ProtoMessage()    {}
func (*ProtoStatItemValue_ProtoDataValue) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

func (m *ProtoStatItemValue_ProtoDataValue) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetSum() uint32 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue) GetBitmapValues() []*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue {
	if m != nil {
		return m.BitmapValues
	}
	return nil
}

type ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue struct {
	Index            *uint32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	BitMap           *uint64 `protobuf:"varint,2,req,name=bit_map,json=bitMap" json:"bit_map,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) Reset() {
	*m = ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue{}
}
func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) ProtoMessage() {}
func (*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0, 0}
}

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue) GetBitMap() uint64 {
	if m != nil && m.BitMap != nil {
		return *m.BitMap
	}
	return 0
}

type ProtoStatItemValue_ProtoStatObjKey struct {
	Self             *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj   `protobuf:"bytes,1,req,name=self" json:"self,omitempty"`
	Associates       []*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj `protobuf:"bytes,2,rep,name=associates" json:"associates,omitempty"`
	StatType         *uint32                                            `protobuf:"varint,3,req,name=stat_type,json=statType" json:"stat_type,omitempty"`
	XXX_unrecognized []byte                                             `json:"-"`
}

func (m *ProtoStatItemValue_ProtoStatObjKey) Reset()         { *m = ProtoStatItemValue_ProtoStatObjKey{} }
func (m *ProtoStatItemValue_ProtoStatObjKey) String() string { return proto.CompactTextString(m) }
func (*ProtoStatItemValue_ProtoStatObjKey) ProtoMessage()    {}
func (*ProtoStatItemValue_ProtoStatObjKey) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1}
}

func (m *ProtoStatItemValue_ProtoStatObjKey) GetSelf() *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *ProtoStatItemValue_ProtoStatObjKey) GetAssociates() []*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj {
	if m != nil {
		return m.Associates
	}
	return nil
}

func (m *ProtoStatItemValue_ProtoStatObjKey) GetStatType() uint32 {
	if m != nil && m.StatType != nil {
		return *m.StatType
	}
	return 0
}

type ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj struct {
	ObjId            *string `protobuf:"bytes,1,req,name=obj_id,json=objId" json:"obj_id,omitempty"`
	ObjType          *uint32 `protobuf:"varint,2,req,name=obj_type,json=objType" json:"obj_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) Reset() {
	*m = ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj{}
}
func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) ProtoMessage() {}
func (*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 1, 0}
}

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) GetObjId() string {
	if m != nil && m.ObjId != nil {
		return *m.ObjId
	}
	return ""
}

func (m *ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj) GetObjType() uint32 {
	if m != nil && m.ObjType != nil {
		return *m.ObjType
	}
	return 0
}

// =============================================================================================================================
// 物理链路状态变化事件值定义
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkChangeNotify struct {
	PhysicalLinkId   *string                                          `protobuf:"bytes,1,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	OldState         *ProtoPhysicalLinkChangeNotify_PhysicalLinkState `protobuf:"varint,2,req,name=old_state,json=oldState,enum=redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState" json:"old_state,omitempty"`
	NewState         *ProtoPhysicalLinkChangeNotify_PhysicalLinkState `protobuf:"varint,3,req,name=new_state,json=newState,enum=redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState" json:"new_state,omitempty"`
	XXX_unrecognized []byte                                           `json:"-"`
}

func (m *ProtoPhysicalLinkChangeNotify) Reset()                    { *m = ProtoPhysicalLinkChangeNotify{} }
func (m *ProtoPhysicalLinkChangeNotify) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkChangeNotify) ProtoMessage()               {}
func (*ProtoPhysicalLinkChangeNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ProtoPhysicalLinkChangeNotify) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkChangeNotify) GetOldState() ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	if m != nil && m.OldState != nil {
		return *m.OldState
	}
	return ProtoPhysicalLinkChangeNotify_ONLINE
}

func (m *ProtoPhysicalLinkChangeNotify) GetNewState() ProtoPhysicalLinkChangeNotify_PhysicalLinkState {
	if m != nil && m.NewState != nil {
		return *m.NewState
	}
	return ProtoPhysicalLinkChangeNotify_ONLINE
}

// =============================================================================================================================
// 物理链路销毁事件值定义
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkDestroyNotify struct {
	PhysicalLinkId   *string `protobuf:"bytes,1,req,name=physical_link_id,json=physicalLinkId" json:"physical_link_id,omitempty"`
	Direction        *uint32 `protobuf:"varint,2,req,name=direction" json:"direction,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoPhysicalLinkDestroyNotify) Reset()                    { *m = ProtoPhysicalLinkDestroyNotify{} }
func (m *ProtoPhysicalLinkDestroyNotify) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkDestroyNotify) ProtoMessage()               {}
func (*ProtoPhysicalLinkDestroyNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ProtoPhysicalLinkDestroyNotify) GetPhysicalLinkId() string {
	if m != nil && m.PhysicalLinkId != nil {
		return *m.PhysicalLinkId
	}
	return ""
}

func (m *ProtoPhysicalLinkDestroyNotify) GetDirection() uint32 {
	if m != nil && m.Direction != nil {
		return *m.Direction
	}
	return 0
}

// =============================================================================================================================
// 物理链路事件汇报指令格式
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkEvent struct {
	OwnerId   *uint32 `protobuf:"varint,1,req,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	OwnerType *uint32 `protobuf:"varint,2,req,name=owner_type,json=ownerType" json:"owner_type,omitempty"`
	EventType *uint32 `protobuf:"varint,3,req,name=event_type,json=eventType" json:"event_type,omitempty"`
	// 			2   被动方创建物理链路成功
	// 			3   主动方关闭物理链路
	// 			4   被动方关闭物理链路
	// 			5   主动方物理链路状态变化
	// 			6   被动方物理链路状态变化
	// 			7   传输控制计算链路质量
	// 			8   传输控制负载均衡后质量
	// 			101 仿真机链路配置信息信息
	BasicInfo        *ProtoPhysicalLinkInfo          `protobuf:"bytes,4,opt,name=basic_info,json=basicInfo" json:"basic_info,omitempty"`
	ChangeNotify     *ProtoPhysicalLinkChangeNotify  `protobuf:"bytes,5,opt,name=change_notify,json=changeNotify" json:"change_notify,omitempty"`
	DestroyNotify    *ProtoPhysicalLinkDestroyNotify `protobuf:"bytes,6,opt,name=destroy_notify,json=destroyNotify" json:"destroy_notify,omitempty"`
	LinkQuality      *ProtoPhysicalLinkQuality       `protobuf:"bytes,7,opt,name=link_quality,json=linkQuality" json:"link_quality,omitempty"`
	Timestamp        *uint64                         `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ProtoPhysicalLinkEvent) Reset()                    { *m = ProtoPhysicalLinkEvent{} }
func (m *ProtoPhysicalLinkEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkEvent) ProtoMessage()               {}
func (*ProtoPhysicalLinkEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ProtoPhysicalLinkEvent) GetOwnerId() uint32 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetOwnerType() uint32 {
	if m != nil && m.OwnerType != nil {
		return *m.OwnerType
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetEventType() uint32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *ProtoPhysicalLinkEvent) GetBasicInfo() *ProtoPhysicalLinkInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetChangeNotify() *ProtoPhysicalLinkChangeNotify {
	if m != nil {
		return m.ChangeNotify
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetDestroyNotify() *ProtoPhysicalLinkDestroyNotify {
	if m != nil {
		return m.DestroyNotify
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetLinkQuality() *ProtoPhysicalLinkQuality {
	if m != nil {
		return m.LinkQuality
	}
	return nil
}

func (m *ProtoPhysicalLinkEvent) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// =============================================================================================================================
// 物理链路统计数据汇报格式
// @since 2.0
// @date 2018/2/1
type ProtoPhysicalLinkStatData struct {
	OwnerId          *uint32             `protobuf:"varint,1,req,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	OwnerType        *uint32             `protobuf:"varint,2,req,name=owner_type,json=ownerType" json:"owner_type,omitempty"`
	ItemValue        *ProtoStatItemValue `protobuf:"bytes,3,req,name=item_value,json=itemValue" json:"item_value,omitempty"`
	Timestamp        *uint64             `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoPhysicalLinkStatData) Reset()                    { *m = ProtoPhysicalLinkStatData{} }
func (m *ProtoPhysicalLinkStatData) String() string            { return proto.CompactTextString(m) }
func (*ProtoPhysicalLinkStatData) ProtoMessage()               {}
func (*ProtoPhysicalLinkStatData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ProtoPhysicalLinkStatData) GetOwnerId() uint32 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *ProtoPhysicalLinkStatData) GetOwnerType() uint32 {
	if m != nil && m.OwnerType != nil {
		return *m.OwnerType
	}
	return 0
}

func (m *ProtoPhysicalLinkStatData) GetItemValue() *ProtoStatItemValue {
	if m != nil {
		return m.ItemValue
	}
	return nil
}

func (m *ProtoPhysicalLinkStatData) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// =============================================================================================================================
// 日志文件的数据编码结构
// @since 1.0
type ProtoMessage struct {
	UserInfo           *ProtoUserInfo             `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	RelayInfo          *ProtoRelayInfo            `protobuf:"bytes,2,opt,name=relay_info,json=relayInfo" json:"relay_info,omitempty"`
	MulticastInfo      *ProtoMulticastInfo        `protobuf:"bytes,3,opt,name=multicast_info,json=multicastInfo" json:"multicast_info,omitempty"`
	MulticastEventInfo *ProtoMulticastEventInfo   `protobuf:"bytes,4,opt,name=multicast_event_info,json=multicastEventInfo" json:"multicast_event_info,omitempty"`
	NicList            *ProtoNicList              `protobuf:"bytes,5,opt,name=nic_list,json=nicList" json:"nic_list,omitempty"`
	LinkEvent          *ProtoPhysicalLinkEvent    `protobuf:"bytes,6,opt,name=link_event,json=linkEvent" json:"link_event,omitempty"`
	StatData           *ProtoPhysicalLinkStatData `protobuf:"bytes,7,opt,name=stat_data,json=statData" json:"stat_data,omitempty"`
	XXX_unrecognized   []byte                     `json:"-"`
}

func (m *ProtoMessage) Reset()                    { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()               {}
func (*ProtoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProtoMessage) GetUserInfo() *ProtoUserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *ProtoMessage) GetRelayInfo() *ProtoRelayInfo {
	if m != nil {
		return m.RelayInfo
	}
	return nil
}

func (m *ProtoMessage) GetMulticastInfo() *ProtoMulticastInfo {
	if m != nil {
		return m.MulticastInfo
	}
	return nil
}

func (m *ProtoMessage) GetMulticastEventInfo() *ProtoMulticastEventInfo {
	if m != nil {
		return m.MulticastEventInfo
	}
	return nil
}

func (m *ProtoMessage) GetNicList() *ProtoNicList {
	if m != nil {
		return m.NicList
	}
	return nil
}

func (m *ProtoMessage) GetLinkEvent() *ProtoPhysicalLinkEvent {
	if m != nil {
		return m.LinkEvent
	}
	return nil
}

func (m *ProtoMessage) GetStatData() *ProtoPhysicalLinkStatData {
	if m != nil {
		return m.StatData
	}
	return nil
}

// =============================================================================================================================
// 实时数据传输结构
type ProtoMonitorMessage struct {
	Type             *ProtoMonitorMessage_MessageType `protobuf:"varint,1,req,name=type,enum=redsdn.ProtoMonitorMessage_MessageType" json:"type,omitempty"`
	CommandId        *string                          `protobuf:"bytes,2,req,name=command_id,json=commandId" json:"command_id,omitempty"`
	Msg              [][]byte                         `protobuf:"bytes,3,rep,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ProtoMonitorMessage) Reset()                    { *m = ProtoMonitorMessage{} }
func (m *ProtoMonitorMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtoMonitorMessage) ProtoMessage()               {}
func (*ProtoMonitorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ProtoMonitorMessage) GetType() ProtoMonitorMessage_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProtoMonitorMessage_USER_INFO
}

func (m *ProtoMonitorMessage) GetCommandId() string {
	if m != nil && m.CommandId != nil {
		return *m.CommandId
	}
	return ""
}

func (m *ProtoMonitorMessage) GetMsg() [][]byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoPhysicalLinkInfo)(nil), "redsdn.ProtoPhysicalLinkInfo")
	proto.RegisterType((*ProtoPhysicalLinkQuality)(nil), "redsdn.ProtoPhysicalLinkQuality")
	proto.RegisterType((*ProtoNicList)(nil), "redsdn.ProtoNicList")
	proto.RegisterType((*ProtoNicList_NicInfo)(nil), "redsdn.ProtoNicList.NicInfo")
	proto.RegisterType((*ProtoUserInfo)(nil), "redsdn.ProtoUserInfo")
	proto.RegisterType((*ProtoEndPointAddress)(nil), "redsdn.ProtoEndPointAddress")
	proto.RegisterType((*ProtoRelayInfo)(nil), "redsdn.ProtoRelayInfo")
	proto.RegisterType((*ProtoMulticastLinkInfo)(nil), "redsdn.ProtoMulticastLinkInfo")
	proto.RegisterType((*ProtoMulticastInfo)(nil), "redsdn.ProtoMulticastInfo")
	proto.RegisterType((*ProtoMulticastEventInfo)(nil), "redsdn.ProtoMulticastEventInfo")
	proto.RegisterType((*ProtoStatItemValue)(nil), "redsdn.ProtoStatItemValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoDataValue)(nil), "redsdn.ProtoStatItemValue.ProtoDataValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoDataValue_ProtoBitmapValue)(nil), "redsdn.ProtoStatItemValue.ProtoDataValue.ProtoBitmapValue")
	proto.RegisterType((*ProtoStatItemValue_ProtoStatObjKey)(nil), "redsdn.ProtoStatItemValue.ProtoStatObjKey")
	proto.RegisterType((*ProtoStatItemValue_ProtoStatObjKey_ProtoStatObj)(nil), "redsdn.ProtoStatItemValue.ProtoStatObjKey.ProtoStatObj")
	proto.RegisterType((*ProtoPhysicalLinkChangeNotify)(nil), "redsdn.ProtoPhysicalLinkChangeNotify")
	proto.RegisterType((*ProtoPhysicalLinkDestroyNotify)(nil), "redsdn.ProtoPhysicalLinkDestroyNotify")
	proto.RegisterType((*ProtoPhysicalLinkEvent)(nil), "redsdn.ProtoPhysicalLinkEvent")
	proto.RegisterType((*ProtoPhysicalLinkStatData)(nil), "redsdn.ProtoPhysicalLinkStatData")
	proto.RegisterType((*ProtoMessage)(nil), "redsdn.ProtoMessage")
	proto.RegisterType((*ProtoMonitorMessage)(nil), "redsdn.ProtoMonitorMessage")
	proto.RegisterEnum("redsdn.ProtoEndPointAddress_IPVersion", ProtoEndPointAddress_IPVersion_name, ProtoEndPointAddress_IPVersion_value)
	proto.RegisterEnum("redsdn.ProtoMulticastLinkInfo_NodeType", ProtoMulticastLinkInfo_NodeType_name, ProtoMulticastLinkInfo_NodeType_value)
	proto.RegisterEnum("redsdn.ProtoMulticastInfo_OperationType", ProtoMulticastInfo_OperationType_name, ProtoMulticastInfo_OperationType_value)
	proto.RegisterEnum("redsdn.ProtoPhysicalLinkChangeNotify_PhysicalLinkState", ProtoPhysicalLinkChangeNotify_PhysicalLinkState_name, ProtoPhysicalLinkChangeNotify_PhysicalLinkState_value)
	proto.RegisterEnum("redsdn.ProtoMonitorMessage_MessageType", ProtoMonitorMessage_MessageType_name, ProtoMonitorMessage_MessageType_value)
}

func init() { proto.RegisterFile("redsdn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x49, 0x73, 0x1b, 0xc7,
	0xf5, 0x17, 0x06, 0x20, 0x96, 0x07, 0x0c, 0x08, 0xb5, 0x29, 0x11, 0x26, 0xb5, 0x50, 0xf8, 0xfb,
	0xaf, 0x50, 0xae, 0x14, 0x53, 0xc5, 0x72, 0x6c, 0x47, 0x4e, 0x5c, 0x81, 0xb8, 0x94, 0x61, 0x91,
	0x20, 0x3d, 0xa0, 0xe8, 0xf2, 0x69, 0xaa, 0x31, 0xd3, 0x24, 0x5b, 0x9a, 0x05, 0x99, 0x6e, 0x50,
	0x62, 0x4e, 0xb9, 0xe5, 0x1b, 0xe4, 0x96, 0x54, 0x0e, 0xb9, 0xa5, 0x92, 0x43, 0x8e, 0xb9, 0xe4,
	0x73, 0xe4, 0x9a, 0x4f, 0x90, 0x2f, 0x90, 0xaa, 0x54, 0xbf, 0xee, 0x19, 0xcc, 0x80, 0x4b, 0x28,
	0xfb, 0x34, 0xdd, 0x6f, 0xeb, 0x9e, 0xb7, 0xfc, 0xfa, 0x75, 0x43, 0x2b, 0x61, 0xbe, 0xf0, 0xa3,
	0x8d, 0x49, 0x12, 0xcb, 0x98, 0x54, 0xf5, 0xac, 0xf7, 0x77, 0x0b, 0xee, 0x1d, 0x2a, 0xca, 0xe1,
	0xd9, 0x85, 0xe0, 0x1e, 0x0d, 0xf6, 0x78, 0xf4, 0x66, 0x10, 0x9d, 0xc4, 0x64, 0x1d, 0x3a, 0x13,
	0x43, 0x73, 0x03, 0x1e, 0xbd, 0x71, 0xb9, 0xdf, 0x2d, 0xad, 0x59, 0xeb, 0x0d, 0xa7, 0x3d, 0xc9,
	0xcb, 0xfa, 0xe4, 0x01, 0x34, 0x7c, 0x9e, 0x30, 0x4f, 0xf2, 0x38, 0xea, 0x5a, 0x6b, 0xd6, 0xba,
	0xed, 0xcc, 0x08, 0xe4, 0x23, 0x68, 0x07, 0xb1, 0x32, 0x12, 0x31, 0xe9, 0xca, 0x8b, 0x09, 0xeb,
	0x96, 0x51, 0xa4, 0x85, 0xd4, 0x21, 0x93, 0x47, 0x17, 0x13, 0x46, 0x1e, 0x02, 0x68, 0x29, 0xea,
	0xfb, 0x49, 0xb7, 0x82, 0xeb, 0x34, 0x90, 0xd2, 0xf7, 0xfd, 0x84, 0xf4, 0xc0, 0xf6, 0x99, 0x90,
	0x33, 0x1b, 0x0b, 0x68, 0xa3, 0xa9, 0x88, 0xa9, 0x89, 0x55, 0x68, 0xa0, 0x0c, 0x5a, 0xa8, 0xa2,
	0x85, 0xba, 0x22, 0xa0, 0x81, 0x55, 0x68, 0x24, 0x71, 0xc0, 0xb4, 0x72, 0x0d, 0x95, 0xeb, 0x8a,
	0x90, 0x6a, 0x4a, 0xee, 0xbd, 0x71, 0x25, 0x0f, 0x59, 0xb7, 0xbe, 0x66, 0xad, 0x57, 0x9c, 0xba,
	0x22, 0x1c, 0xf1, 0x90, 0x91, 0x0f, 0xa1, 0x3e, 0x95, 0x9e, 0xe6, 0x35, 0x90, 0x57, 0x9b, 0x4a,
	0x4f, 0xb1, 0x7a, 0xff, 0xaa, 0x40, 0xf7, 0x92, 0xf3, 0xbe, 0x99, 0xd2, 0x80, 0xcb, 0x8b, 0xf7,
	0xf0, 0x5f, 0x07, 0xca, 0xdc, 0x7f, 0xd7, 0xb5, 0xd6, 0x4a, 0xeb, 0xb6, 0xa3, 0x86, 0x8a, 0x92,
	0x48, 0x69, 0x1c, 0xa5, 0x86, 0x6a, 0x8b, 0x41, 0x2c, 0x84, 0x9b, 0x50, 0xc9, 0xd0, 0x3d, 0xb6,
	0x53, 0x57, 0x04, 0x87, 0x4a, 0x46, 0xee, 0x43, 0xf5, 0x35, 0x97, 0x92, 0x25, 0xc6, 0x2d, 0x66,
	0x56, 0x0c, 0x4c, 0x75, 0x3e, 0x30, 0x0f, 0x01, 0xc6, 0x34, 0xf2, 0xdd, 0xb7, 0xdc, 0x97, 0x67,
	0xc6, 0x27, 0x0d, 0x45, 0xf9, 0x56, 0x11, 0xd4, 0xfe, 0x69, 0x10, 0xc4, 0x9e, 0x9b, 0x13, 0xaa,
	0xa3, 0x50, 0x1b, 0xe9, 0x2f, 0x32, 0xc9, 0x6d, 0x78, 0x1c, 0xd2, 0x77, 0xae, 0x17, 0x47, 0x82,
	0x79, 0x53, 0xc9, 0xcf, 0x99, 0x8b, 0x7b, 0x9d, 0x50, 0xef, 0x0d, 0x93, 0xae, 0x98, 0x86, 0xe8,
	0x38, 0xdb, 0x59, 0x0d, 0xe9, 0xbb, 0xad, 0x99, 0xd4, 0x5e, 0x2c, 0xc4, 0x21, 0xca, 0x8c, 0xa6,
	0x21, 0xf9, 0x0c, 0xba, 0xca, 0xca, 0x34, 0x8a, 0x13, 0x9f, 0x25, 0xcc, 0xcf, 0xab, 0x03, 0xaa,
	0xdf, 0x0b, 0xe9, 0xbb, 0x57, 0x29, 0x7b, 0xa6, 0xa8, 0x42, 0x2b, 0xa5, 0x1b, 0xb0, 0x73, 0x16,
	0x74, 0x9b, 0x26, 0xb4, 0x52, 0xee, 0xa9, 0x39, 0x79, 0x0a, 0x8b, 0x99, 0xdf, 0x8c, 0x48, 0x0b,
	0x45, 0xec, 0xd4, 0x7b, 0x5a, 0xee, 0x19, 0x74, 0x84, 0xa4, 0x63, 0xae, 0x42, 0xe7, 0x9e, 0x50,
	0x4f, 0xc6, 0x49, 0xd7, 0x5e, 0xb3, 0xd6, 0xef, 0x3a, 0x8b, 0x19, 0x7d, 0x17, 0xc9, 0x64, 0x09,
	0x16, 0x64, 0xc2, 0x22, 0xbf, 0xdb, 0x46, 0x43, 0x7a, 0x42, 0x1e, 0x43, 0x93, 0x45, 0x74, 0x1c,
	0x30, 0xf7, 0x24, 0xa0, 0xa7, 0xdd, 0x45, 0xd4, 0x05, 0x4d, 0xda, 0x0d, 0xe8, 0x69, 0x31, 0xc9,
	0x3a, 0x37, 0x24, 0xd9, 0xdd, 0x62, 0x92, 0x71, 0x68, 0x61, 0x8e, 0x0d, 0xb9, 0xb7, 0xc7, 0x85,
	0x24, 0x1b, 0x50, 0x8e, 0xb8, 0xd7, 0x2d, 0xad, 0x95, 0xd7, 0x9b, 0x9b, 0x0f, 0x36, 0x4c, 0x55,
	0xe7, 0x45, 0x36, 0x86, 0xdc, 0x53, 0x25, 0xec, 0x28, 0xc1, 0x95, 0x67, 0x50, 0x33, 0x73, 0xd2,
	0x06, 0x2b, 0x4b, 0x42, 0x8b, 0xfb, 0x38, 0x9f, 0x60, 0xc5, 0xaa, 0xf9, 0xa4, 0xf7, 0xcf, 0x12,
	0xd8, 0x68, 0xe8, 0x95, 0x60, 0x09, 0x6a, 0x2c, 0x43, 0x6d, 0x2a, 0x58, 0x92, 0xe6, 0x6e, 0xc5,
	0xa9, 0xaa, 0xe9, 0xc0, 0x57, 0x7f, 0x83, 0x0c, 0xac, 0x27, 0x5d, 0xf3, 0x75, 0x45, 0xc0, 0x7a,
	0x7a, 0x0c, 0x4d, 0x9f, 0x9d, 0x73, 0x8f, 0xe5, 0xeb, 0x1d, 0x34, 0x09, 0x05, 0xda, 0x60, 0xc5,
	0xc2, 0x54, 0xb9, 0x15, 0x0b, 0xf4, 0x7e, 0x7c, 0x22, 0xdf, 0xd2, 0x84, 0xb9, 0xe7, 0x2c, 0x11,
	0x2a, 0x5f, 0x17, 0x90, 0xbb, 0x98, 0xd2, 0x8f, 0x35, 0xb9, 0xe8, 0xc6, 0xea, 0x0d, 0x6e, 0xac,
	0x15, 0xdd, 0xf8, 0xfb, 0x12, 0x2c, 0xe1, 0xbf, 0xed, 0x44, 0xfe, 0x61, 0xcc, 0x23, 0x84, 0x05,
	0x26, 0x04, 0xd9, 0x86, 0x5a, 0xba, 0xa4, 0xfa, 0xc5, 0xf6, 0xe6, 0xd3, 0x82, 0x4f, 0xe7, 0xc4,
	0x37, 0x06, 0x87, 0x66, 0x27, 0xcf, 0xad, 0xe3, 0x4f, 0x9c, 0x54, 0x75, 0xde, 0x95, 0x84, 0x40,
	0x65, 0x12, 0x27, 0x69, 0x09, 0xe3, 0xb8, 0xb7, 0x0a, 0x8d, 0x4c, 0x9b, 0x54, 0xc1, 0x3a, 0xfe,
	0xa4, 0x73, 0x07, 0xbf, 0x9f, 0x76, 0x4a, 0xbd, 0xff, 0x2c, 0x40, 0x1b, 0x17, 0x74, 0x58, 0x40,
	0x2f, 0xd0, 0xf9, 0x4b, 0xb0, 0xc0, 0x23, 0x9f, 0xbd, 0xc3, 0x7d, 0xd9, 0x8e, 0x9e, 0xa8, 0xb2,
	0x4d, 0x94, 0x88, 0x1b, 0xd1, 0x90, 0x99, 0x15, 0x1b, 0x48, 0x19, 0xd2, 0x90, 0x91, 0x7b, 0x50,
	0xe5, 0xbe, 0xa7, 0x02, 0x56, 0x36, 0x5a, 0xbe, 0x37, 0xf0, 0x15, 0x44, 0xf8, 0x71, 0x48, 0x79,
	0x64, 0xbc, 0x6e, 0x66, 0xe4, 0x09, 0xb4, 0xf4, 0xc8, 0xd5, 0x4b, 0xa5, 0xb8, 0x8a, 0xb4, 0x01,
	0x2e, 0xa8, 0xe0, 0x49, 0x4c, 0x0c, 0xa2, 0xaa, 0xa1, 0x8a, 0x01, 0x17, 0x13, 0xa3, 0x61, 0xc0,
	0x94, 0x8b, 0x89, 0x16, 0xef, 0x83, 0x1d, 0x32, 0x9f, 0x53, 0xc4, 0x61, 0x26, 0x04, 0x82, 0xc6,
	0x7c, 0xa6, 0xce, 0x79, 0xd5, 0x69, 0xa1, 0x4a, 0x1a, 0x12, 0x17, 0x1e, 0x86, 0xd3, 0x40, 0x72,
	0x8f, 0x0a, 0xe9, 0x0a, 0x16, 0x30, 0x4f, 0xba, 0x13, 0x2a, 0xcf, 0x32, 0x93, 0x8d, 0x5b, 0x98,
	0x5c, 0xc9, 0x4c, 0x8c, 0xd0, 0xc2, 0x21, 0x95, 0x67, 0xe9, 0x02, 0x7d, 0xb0, 0xf9, 0x84, 0x25,
	0x27, 0x99, 0x41, 0xb8, 0xcd, 0x1e, 0x51, 0x25, 0x35, 0xf1, 0x39, 0x74, 0x15, 0xa6, 0xf8, 0x6e,
	0x3c, 0x95, 0xe3, 0x78, 0x1a, 0xf9, 0x88, 0x93, 0x1a, 0x26, 0x35, 0x08, 0xdd, 0x47, 0xfe, 0x81,
	0x61, 0xbf, 0x48, 0xb9, 0xe4, 0x53, 0x58, 0xd6, 0x9a, 0x3c, 0x9a, 0x57, 0xd4, 0xd0, 0x74, 0x0f,
	0xd9, 0x83, 0x68, 0x4e, 0x6f, 0x13, 0x34, 0xc3, 0x35, 0x60, 0x1b, 0x69, 0x1c, 0x17, 0x88, 0x53,
	0xb6, 0xf3, 0x01, 0x32, 0xf7, 0x11, 0x61, 0x53, 0x16, 0xf9, 0x31, 0x90, 0x99, 0x8e, 0x60, 0x42,
	0xa0, 0x82, 0x06, 0xae, 0x4e, 0xaa, 0x30, 0x32, 0x74, 0x4c, 0x2d, 0x94, 0xf6, 0x62, 0x21, 0x11,
	0xc2, 0x6c, 0xa7, 0x81, 0x94, 0xad, 0x58, 0x48, 0xf2, 0x7f, 0xea, 0x10, 0x96, 0xda, 0xb4, 0x1b,
	0x4d, 0x43, 0x44, 0x31, 0xdb, 0x69, 0x65, 0xc4, 0xa1, 0x46, 0xe3, 0x59, 0x7d, 0xde, 0xbd, 0xa1,
	0x3e, 0x49, 0xb1, 0x3e, 0x7f, 0x6b, 0xc1, 0x7d, 0x74, 0xfb, 0x7e, 0x1a, 0xb6, 0xac, 0x13, 0x59,
	0x86, 0x5a, 0x14, 0xfb, 0x2c, 0x05, 0x21, 0xdb, 0xa9, 0xaa, 0xe9, 0xc0, 0x27, 0xdb, 0xd0, 0x40,
	0x46, 0x06, 0x42, 0xed, 0xcd, 0x1f, 0x15, 0x42, 0x78, 0xc9, 0xd6, 0xc6, 0x30, 0xf6, 0x11, 0x82,
	0x9c, 0x7a, 0x64, 0x46, 0xc5, 0xd6, 0xa0, 0x3c, 0xd7, 0x1a, 0x5c, 0x75, 0x8a, 0x57, 0xae, 0x3c,
	0xc5, 0xf1, 0xa4, 0x39, 0x2d, 0x08, 0x2e, 0xa4, 0x27, 0xcd, 0xe9, 0x4c, 0xae, 0xf7, 0x18, 0xea,
	0xe9, 0x26, 0x48, 0x1d, 0x2a, 0xaf, 0x46, 0x3b, 0x4e, 0xe7, 0x0e, 0x69, 0xc0, 0x82, 0xb3, 0xb3,
	0xd7, 0xff, 0xae, 0x53, 0xea, 0xfd, 0xb9, 0x02, 0xa4, 0xb8, 0x7b, 0xf4, 0xc2, 0x13, 0x68, 0xcd,
	0x8a, 0x22, 0xc3, 0xe3, 0x66, 0x46, 0xd3, 0xa0, 0x3c, 0xfb, 0x13, 0x6b, 0xee, 0x4f, 0x72, 0x5e,
	0x2c, 0x17, 0xbc, 0xb8, 0x9a, 0xf7, 0xa2, 0x69, 0x2d, 0x32, 0xe7, 0x3c, 0x87, 0x0f, 0x67, 0xab,
	0x4e, 0xa6, 0xe3, 0x80, 0x8b, 0xb3, 0x1c, 0x44, 0xab, 0x8e, 0x65, 0x39, 0x13, 0x38, 0xd4, 0xfc,
	0x14, 0xe2, 0xbe, 0x84, 0xd5, 0x5c, 0x19, 0x4f, 0xc7, 0xc2, 0x4b, 0xf8, 0x78, 0x06, 0xf0, 0x55,
	0xd4, 0x9e, 0x99, 0x1f, 0xa5, 0x12, 0xa9, 0xfe, 0xe7, 0x50, 0x9b, 0xd0, 0x84, 0x45, 0x52, 0x74,
	0x6b, 0x78, 0xda, 0x3d, 0xba, 0x39, 0xb8, 0x4e, 0x2a, 0x4e, 0x9e, 0x43, 0xdd, 0x3b, 0xe3, 0x81,
	0x9f, 0xb0, 0xa8, 0x5b, 0xbf, 0x95, 0x6a, 0x26, 0x4f, 0x0e, 0xa0, 0x1d, 0x4f, 0x58, 0x42, 0x31,
	0xcb, 0xd1, 0x27, 0x0d, 0xcc, 0xac, 0xf5, 0xab, 0x2d, 0x60, 0x56, 0x1d, 0xa4, 0x0a, 0x98, 0x5a,
	0x76, 0x9c, 0x9f, 0x16, 0x2b, 0x02, 0x6e, 0xa8, 0x88, 0x66, 0xb1, 0x22, 0x3e, 0x02, 0xbb, 0x60,
	0x97, 0xd4, 0xa0, 0xdc, 0xdf, 0xde, 0xee, 0xdc, 0x21, 0x00, 0x55, 0x67, 0x67, 0xff, 0xe0, 0x78,
	0xa7, 0x53, 0xea, 0xfd, 0xa6, 0x0c, 0xcb, 0xc5, 0x1d, 0xed, 0x9c, 0xb3, 0xe8, 0x7d, 0x52, 0x86,
	0x29, 0x79, 0xf7, 0x0d, 0xbb, 0x30, 0x87, 0x49, 0x1d, 0x09, 0x2f, 0xd9, 0x85, 0xc2, 0x03, 0xcd,
	0xcc, 0x4a, 0x63, 0xc1, 0xd1, 0xe2, 0x69, 0xcf, 0xae, 0xd9, 0x3c, 0x3a, 0x89, 0xd3, 0x9e, 0x9d,
	0x65, 0xab, 0xe7, 0x12, 0x6e, 0xe1, 0xfa, 0xb2, 0xad, 0x7e, 0xdf, 0xb2, 0xbd, 0xaa, 0x32, 0x6b,
	0xb7, 0xad, 0xcc, 0xfa, 0x15, 0x95, 0x59, 0x0c, 0x54, 0xe3, 0x86, 0x40, 0x41, 0x31, 0x50, 0x7f,
	0xac, 0x9a, 0x82, 0x1d, 0x49, 0x2a, 0x07, 0x92, 0x85, 0xc7, 0x34, 0x98, 0x32, 0xb2, 0x05, 0xb5,
	0x78, 0xfc, 0x1a, 0x1d, 0x5b, 0xc2, 0xe3, 0xe5, 0xe3, 0xc2, 0x4f, 0x16, 0x84, 0x67, 0xa4, 0x83,
	0xf1, 0xeb, 0x97, 0xec, 0xc2, 0xa9, 0xc6, 0xf8, 0x25, 0x5f, 0x43, 0xd3, 0xa7, 0x92, 0xba, 0xe7,
	0x4a, 0x4a, 0x74, 0x2d, 0x4c, 0xe6, 0x67, 0xff, 0xcb, 0xd0, 0x36, 0x95, 0x14, 0xa7, 0x0e, 0xf8,
	0xe9, 0x50, 0x28, 0xfc, 0x16, 0x92, 0xaa, 0x70, 0x49, 0x96, 0x9c, 0xd3, 0x20, 0xbd, 0x88, 0x29,
	0xe2, 0xc0, 0xd0, 0xc8, 0xc7, 0x70, 0x57, 0x4c, 0xc7, 0x6e, 0x51, 0x50, 0xa3, 0xc2, 0xa2, 0x98,
	0x8e, 0x47, 0x79, 0xd9, 0x07, 0xca, 0x61, 0x21, 0x13, 0x92, 0x86, 0x13, 0x8c, 0x71, 0xc5, 0x99,
	0x11, 0x56, 0xfe, 0x5d, 0x32, 0x1d, 0x4d, 0xb6, 0x9b, 0x6b, 0x3a, 0x9a, 0x0e, 0x94, 0x55, 0x93,
	0xaf, 0x01, 0x4b, 0x0d, 0x55, 0xf7, 0x24, 0xf8, 0xaf, 0x53, 0x34, 0xc6, 0x31, 0x71, 0xc1, 0x1e,
	0x73, 0x19, 0xd2, 0x49, 0xea, 0x8b, 0x0a, 0xfa, 0xe2, 0xf9, 0xad, 0x7d, 0xa1, 0xa7, 0x2f, 0xd0,
	0x86, 0x76, 0x4e, 0x6b, 0x3c, 0x9b, 0x88, 0x95, 0x3e, 0x74, 0xe6, 0x25, 0xae, 0xd9, 0xf0, 0x32,
	0xd4, 0xc6, 0x5c, 0xba, 0x21, 0xd5, 0x1d, 0x5f, 0xc5, 0xa9, 0x8e, 0xb9, 0xdc, 0xa7, 0x93, 0x95,
	0xdf, 0x59, 0xb0, 0x38, 0x17, 0x49, 0xf2, 0x12, 0x2a, 0x82, 0x05, 0x27, 0x26, 0x07, 0x3e, 0xbb,
	0x7d, 0x0e, 0x14, 0xe6, 0x0e, 0x1a, 0x21, 0xdf, 0x02, 0x50, 0x21, 0x62, 0x8f, 0x53, 0x99, 0x65,
	0xc3, 0xf7, 0x36, 0x99, 0x33, 0xa5, 0x72, 0x1f, 0x43, 0x9e, 0x3f, 0x04, 0x15, 0x41, 0x95, 0xda,
	0xca, 0x2f, 0xcd, 0x15, 0xc4, 0x28, 0xaa, 0x1e, 0x53, 0x65, 0x76, 0x76, 0x97, 0x58, 0x88, 0xc7,
	0xaf, 0x07, 0xbe, 0x2a, 0x11, 0x45, 0xce, 0x9d, 0x3e, 0xaa, 0x00, 0x94, 0x85, 0xde, 0xdf, 0x2c,
	0x78, 0x78, 0xe9, 0xa6, 0xbc, 0x75, 0x46, 0xa3, 0x53, 0x36, 0x8c, 0x25, 0x3f, 0x79, 0x9f, 0xeb,
	0xf2, 0x11, 0x34, 0xe2, 0xc0, 0xc7, 0x0c, 0x4d, 0x4f, 0xfd, 0xa2, 0x0b, 0xae, 0x5b, 0x63, 0x23,
	0xcf, 0x50, 0xff, 0xc2, 0x9c, 0x7a, 0x1c, 0xf8, 0x38, 0x52, 0x56, 0x23, 0xf6, 0xd6, 0x58, 0x2d,
	0xff, 0x40, 0xab, 0x11, 0x7b, 0x8b, 0xa3, 0xde, 0x17, 0x70, 0xf7, 0x12, 0x5b, 0xc1, 0xf7, 0xc1,
	0x70, 0x6f, 0x30, 0xdc, 0xe9, 0xdc, 0x21, 0x36, 0x34, 0x76, 0xf7, 0xfa, 0xa3, 0xaf, 0xdc, 0x83,
	0xdd, 0xdd, 0x4e, 0x89, 0x34, 0xa1, 0x76, 0xb0, 0xbb, 0x8b, 0x3c, 0xab, 0x77, 0x06, 0x8f, 0x2e,
	0xad, 0xbc, 0xcd, 0x84, 0x4c, 0xe2, 0x8b, 0xf7, 0x76, 0xda, 0x8d, 0x6f, 0x34, 0xbd, 0xbf, 0x94,
	0x4d, 0xf3, 0x95, 0x5f, 0x0a, 0xcf, 0x11, 0x0c, 0xea, 0xdb, 0x68, 0x76, 0x05, 0x54, 0x41, 0x55,
	0xf3, 0x81, 0xaf, 0xf0, 0x5f, 0xb3, 0x72, 0x11, 0x6f, 0x20, 0xa5, 0x78, 0x3c, 0xe4, 0x72, 0x2a,
	0x77, 0x7a, 0xfc, 0x1c, 0x60, 0x4c, 0x05, 0xf7, 0xd2, 0xd3, 0xa3, 0xb4, 0xde, 0xdc, 0x7c, 0x78,
	0xad, 0xc7, 0xf1, 0x90, 0x6e, 0xa0, 0x02, 0x1e, 0x2e, 0x5f, 0x83, 0xed, 0x61, 0x10, 0xdc, 0x08,
	0x5d, 0x81, 0xbd, 0x48, 0x73, 0xf3, 0xff, 0x6f, 0x15, 0x32, 0xa7, 0xe5, 0xe5, 0x53, 0x6f, 0x1f,
	0xda, 0xbe, 0x76, 0x6b, 0x6a, 0xac, 0x8a, 0xc6, 0x9e, 0x5e, 0x6b, 0xac, 0x10, 0x05, 0xc7, 0xf6,
	0x0b, 0x41, 0xd9, 0x82, 0x16, 0xc6, 0xe2, 0x57, 0xfa, 0x21, 0xa8, 0x5b, 0x43, 0x63, 0x6b, 0xd7,
	0x1a, 0x33, 0x0f, 0x46, 0x4e, 0x33, 0xc8, 0xbd, 0x1e, 0x15, 0xa0, 0xb5, 0x3e, 0x07, 0xad, 0xbd,
	0xbf, 0x96, 0xe0, 0xc3, 0x4b, 0x76, 0x54, 0x72, 0x29, 0xb0, 0xfb, 0x01, 0x21, 0xfb, 0x19, 0x00,
	0x97, 0x2c, 0xd4, 0x08, 0x8b, 0x21, 0x6b, 0x6e, 0xae, 0x5c, 0x0f, 0x2f, 0x4e, 0x83, 0x67, 0xa7,
	0x5d, 0x61, 0xc3, 0x95, 0xf9, 0x0d, 0xff, 0xa3, 0x6c, 0x20, 0x64, 0x9f, 0x09, 0x41, 0x4f, 0x19,
	0xd9, 0x34, 0xef, 0x07, 0x18, 0xfc, 0x12, 0x7a, 0xe8, 0x5e, 0x61, 0xa1, 0xf4, 0x09, 0x42, 0x3f,
	0x2b, 0x60, 0xcc, 0x7f, 0x9a, 0xde, 0x7c, 0x51, 0xc9, 0x42, 0xa5, 0xfb, 0x05, 0xa5, 0xec, 0xee,
	0x6c, 0x6e, 0xc4, 0xa8, 0xd6, 0x87, 0x76, 0xae, 0x0b, 0x52, 0xaa, 0x65, 0x54, 0x5d, 0xb9, 0xbe,
	0xa1, 0x73, 0xec, 0xb0, 0xd0, 0x7b, 0x7f, 0x03, 0x4b, 0x33, 0x13, 0x85, 0x9e, 0x47, 0x19, 0x7a,
	0x7c, 0xb5, 0xa1, 0xac, 0x0f, 0x73, 0x48, 0x78, 0xb9, 0x37, 0xfb, 0x09, 0xd4, 0x23, 0xee, 0xb9,
	0x01, 0x17, 0xd2, 0xe4, 0xee, 0xd2, 0x55, 0x6f, 0x39, 0x4e, 0x2d, 0x32, 0xef, 0x3e, 0xbf, 0x00,
	0xc0, 0xb4, 0xc2, 0xe5, 0x4d, 0x86, 0x3e, 0xba, 0x36, 0xa9, 0x70, 0x21, 0xa7, 0x11, 0x64, 0x75,
	0xfc, 0xa5, 0x01, 0x78, 0xd5, 0x0f, 0x98, 0x94, 0x7c, 0x72, 0xad, 0x76, 0x9a, 0x4a, 0xfa, 0x0c,
	0x50, 0xa3, 0xde, 0x9f, 0x2c, 0xf8, 0x40, 0xff, 0x5f, 0x1c, 0x71, 0x19, 0x27, 0x69, 0x20, 0xbf,
	0x80, 0x0a, 0xe6, 0x52, 0xe9, 0xaa, 0x3e, 0xae, 0x20, 0xba, 0x61, 0xbe, 0xd8, 0xc7, 0xa1, 0x92,
	0x4a, 0x47, 0x2f, 0x0e, 0x43, 0x1a, 0xf9, 0x2a, 0x57, 0xcd, 0x5b, 0x86, 0xa1, 0xe8, 0x87, 0xd1,
	0x50, 0x9c, 0x76, 0xcb, 0x6b, 0xe5, 0xf5, 0x96, 0xa3, 0x86, 0xbd, 0x3f, 0x94, 0xa0, 0x99, 0x33,
	0xa3, 0xe0, 0x53, 0x5d, 0xa0, 0xdc, 0xc1, 0x70, 0xf7, 0xa0, 0x73, 0x87, 0xb4, 0x01, 0xf0, 0x16,
	0xa5, 0xe7, 0x25, 0x42, 0xa0, 0xbd, 0xff, 0x6a, 0xef, 0x68, 0xb0, 0xd5, 0x1f, 0x1d, 0x69, 0x9a,
	0x45, 0xba, 0xb0, 0x34, 0xa3, 0xed, 0x1c, 0xef, 0x0c, 0x0d, 0xa7, 0x4c, 0x5a, 0x50, 0x1f, 0x0e,
	0xb6, 0xdc, 0xbd, 0xc1, 0xe8, 0xa8, 0x53, 0x21, 0xcb, 0xf0, 0xc1, 0xe1, 0x57, 0xdf, 0x8d, 0x06,
	0x5b, 0xfd, 0x3d, 0x77, 0x6f, 0x30, 0x7c, 0xa9, 0x65, 0x3b, 0x0b, 0x64, 0x15, 0x96, 0x8b, 0x8c,
	0xd1, 0x51, 0xff, 0xc8, 0xdd, 0xee, 0x1f, 0xf5, 0x3b, 0xd5, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xe5, 0xf8, 0xf5, 0xc4, 0x66, 0x17, 0x00, 0x00,
}
